//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FlowareUtil.rti.com", ConfigurationName="ServiceReferenceFlowareWebLive.FlowareWebServiceManager")]
    public interface FlowareWebServiceManager {
        
        // CODEGEN: Generating message contract since element name aAct from namespace http://FlowareUtil.rti.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponse createWorkItem(Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponse> createWorkItemAsync(Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createWorkItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createWorkItem", Namespace="http://FlowareUtil.rti.com", Order=0)]
        public Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequestBody Body;
        
        public createWorkItemRequest() {
        }
        
        public createWorkItemRequest(Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://FlowareUtil.rti.com")]
    public partial class createWorkItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aAct;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int aTowId;
        
        public createWorkItemRequestBody() {
        }
        
        public createWorkItemRequestBody(string aAct, int aTowId) {
            this.aAct = aAct;
            this.aTowId = aTowId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createWorkItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createWorkItemResponse", Namespace="http://FlowareUtil.rti.com", Order=0)]
        public Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponseBody Body;
        
        public createWorkItemResponse() {
        }
        
        public createWorkItemResponse(Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://FlowareUtil.rti.com")]
    public partial class createWorkItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createWorkItemReturn;
        
        public createWorkItemResponseBody() {
        }
        
        public createWorkItemResponseBody(int createWorkItemReturn) {
            this.createWorkItemReturn = createWorkItemReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlowareWebServiceManagerChannel : Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlowareWebServiceManagerClient : System.ServiceModel.ClientBase<Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager>, Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager {
        
        public FlowareWebServiceManagerClient() {
        }
        
        public FlowareWebServiceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlowareWebServiceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlowareWebServiceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlowareWebServiceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponse Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager.createWorkItem(Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest request) {
            return base.Channel.createWorkItem(request);
        }
        
        public int createWorkItem(string aAct, int aTowId) {
            Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest inValue = new Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest();
            inValue.Body = new Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequestBody();
            inValue.Body.aAct = aAct;
            inValue.Body.aTowId = aTowId;
            Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponse retVal = ((Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager)(this)).createWorkItem(inValue);
            return retVal.Body.createWorkItemReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponse> Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager.createWorkItemAsync(Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest request) {
            return base.Channel.createWorkItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemResponse> createWorkItemAsync(string aAct, int aTowId) {
            Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest inValue = new Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequest();
            inValue.Body = new Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.createWorkItemRequestBody();
            inValue.Body.aAct = aAct;
            inValue.Body.aTowId = aTowId;
            return ((Rti.DocumentManagerServer.ServiceReferenceFlowareWebLive.FlowareWebServiceManager)(this)).createWorkItemAsync(inValue);
        }
    }
}
