//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RETURN_STATES
    {
        public long ACT_RETSTATE_ID { get; set; }
        public long ACT_NAME_ID { get; set; }
        public string RETURN_STATE { get; set; }
    }
}
