//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_NAMES
    {
        public long ACT_NAME_ID { get; set; }
        public string ACT_NAME { get; set; }
        public long ACT_TYPE { get; set; }
        public long ACT_ATTR { get; set; }
        public long DEFAULT_PRIORITY { get; set; }
        public string ACT_NAME_CMD { get; set; }
        public long TIME_STAMP { get; set; }
        public long NBR_RETURN_STATES { get; set; }
        public long FW { get; set; }
    }
}
