//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERT
    {
        public ALERT()
        {
            this.CHANNEL_ALERT = new HashSet<CHANNEL_ALERT>();
            this.ALERT_EMAIL = new HashSet<ALERT_EMAIL>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string IS_ENABLED { get; set; }
        public string EXPRESSION { get; set; }
        public string TEMPLATE { get; set; }
        public string SUBJECT { get; set; }
    
        public virtual ICollection<CHANNEL_ALERT> CHANNEL_ALERT { get; set; }
        public virtual ICollection<ALERT_EMAIL> ALERT_EMAIL { get; set; }
    }
}
