//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRACTIVATIONHDR
    {
        public decimal AMRACTIVATIONHDR_ID { get; set; }
        public decimal CLIENTKEY { get; set; }
        public System.DateTime GENERATEDATE { get; set; }
        public string RPTTYPE { get; set; }
        public string RPTHDR_LINE1 { get; set; }
        public string RPTHDR_LINE2 { get; set; }
        public string RPTHDR_LINE3 { get; set; }
    }
}
