//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRACTIVATIONEXCEPTION
    {
        public decimal AMRACTIVATIONEXCEPTION_ID { get; set; }
        public string PARDOCNO { get; set; }
        public string ENCTRNO { get; set; }
        public System.DateTime DOS { get; set; }
        public string PAT_LNAME { get; set; }
        public string PAT_FNAME { get; set; }
        public string PROC_STATUS { get; set; }
        public string EXCPT_CODE { get; set; }
    }
}
