//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRCLAIM
    {
        public Nullable<decimal> AMRCLAIM_ID { get; set; }
        public string ENCTR_NO { get; set; }
        public string ACCT_NO { get; set; }
        public string PRACTICE { get; set; }
        public Nullable<System.DateTime> SERVICE_DATE { get; set; }
        public string DIVISION { get; set; }
        public string REASON { get; set; }
        public string HOLD_PAYOR { get; set; }
        public string EOB_PAYOR { get; set; }
        public string STATUS { get; set; }
        public string START_ACTIVITY { get; set; }
        public string DOCNO { get; set; }
        public string DOCTYPE { get; set; }
        public Nullable<decimal> IFNDS { get; set; }
        public Nullable<decimal> IFNID { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string WHO { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
