//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRDISCOVERY_VIEW3
    {
        public Nullable<System.DateTime> DOS { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string START_ACTIVITY { get; set; }
        public Nullable<decimal> ITEMCOUNT { get; set; }
        public Nullable<decimal> DAILYTRIPS { get; set; }
        public string WHO { get; set; }
        public string LOB { get; set; }
        public string TOB { get; set; }
        public Nullable<decimal> MONTH { get; set; }
        public Nullable<decimal> YEAR { get; set; }
        public Nullable<System.DateTime> REFRESHDATE { get; set; }
    }
}
