//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRDISCOVERY_VIEW2
    {
        public Nullable<System.DateTime> DOS { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public Nullable<decimal> DAILYITEMS { get; set; }
        public Nullable<System.DateTime> REFRESHDATE { get; set; }
    }
}
