//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRPOSTWAKE
    {
        public long COURIER_INST_ID { get; set; }
        public string ACTION { get; set; }
        public long COURIER_ID { get; set; }
        public string PROCESSSTATUS { get; set; }
        public Nullable<System.DateTime> PROCESSDATE { get; set; }
        public Nullable<int> PROCESSATTEMPTS { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
        public Nullable<int> AMRPOSTWAKE_ID { get; set; }
    }
}
