//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMRPOST
    {
        public Nullable<decimal> NPAGES { get; set; }
        public Nullable<decimal> IFNDS { get; set; }
        public Nullable<decimal> IFNID { get; set; }
        public Nullable<decimal> SLEVEL { get; set; }
        public string DOCNO { get; set; }
        public string PARDOCNO { get; set; }
        public string ORIGDOC { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string ACCTNUM { get; set; }
        public string EMBACCT { get; set; }
        public string CHECKNUM { get; set; }
        public string CHECKAMT { get; set; }
        public Nullable<System.DateTime> DEPDT { get; set; }
        public string EXTPAYOR { get; set; }
        public string DEPCODE { get; set; }
        public string DOCGROUP { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCDET { get; set; }
        public string STATUS { get; set; }
        public string RLFLAG { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public Nullable<System.DateTime> SCANDATE { get; set; }
        public string SCANTIME { get; set; }
        public string SCANUID { get; set; }
        public string SOURCEID { get; set; }
        public string BOXNUM { get; set; }
        public string EXPSTAT { get; set; }
        public string SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<System.DateTime> SPARE3 { get; set; }
        public string ENCTRNO { get; set; }
        public string TOB { get; set; }
        public string LOB { get; set; }
        public string INVOICE { get; set; }
        public decimal TOWID { get; set; }
    }
}
