//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNOTTBL
    {
        public Nullable<decimal> IMGIFNDS { get; set; }
        public Nullable<decimal> IMGIFNID { get; set; }
        public Nullable<decimal> IMGPAGE { get; set; }
        public Nullable<decimal> NPAGES { get; set; }
        public Nullable<decimal> ANTIFNDS { get; set; }
        public Nullable<decimal> ANTIFNID { get; set; }
        public decimal TOWID { get; set; }
    }
}
