//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHMENT
    {
        public string ID { get; set; }
        public string MESSAGE_ID { get; set; }
        public byte[] ATTACHMENT_DATA { get; set; }
        public Nullable<decimal> ATTACHMENT_SIZE { get; set; }
        public string ATTACHMENT_TYPE { get; set; }
    }
}
