//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class B4D
    {
        public Nullable<decimal> DOCNUM { get; set; }
        public Nullable<decimal> DOCID { get; set; }
        public Nullable<decimal> DOCSZ { get; set; }
        public Nullable<decimal> DSTAT { get; set; }
        public Nullable<decimal> BADOCR { get; set; }
        public Nullable<decimal> OCRCNT { get; set; }
        public string DSTRUCT { get; set; }
        public decimal TOWID { get; set; }
    }
}
