//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_LIST
    {
        public string BIDENT { get; set; }
        public string BTITLE { get; set; }
        public Nullable<decimal> IFNDS { get; set; }
        public Nullable<decimal> IFNID { get; set; }
        public string C_USER { get; set; }
        public Nullable<decimal> C_TIME { get; set; }
        public Nullable<decimal> SZ_DCS { get; set; }
        public Nullable<decimal> DOC_NO { get; set; }
        public Nullable<decimal> SZ_PGS { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> SLEVEL { get; set; }
        public string USER_ID { get; set; }
        public string APPLIC { get; set; }
        public string COMMENTS { get; set; }
        public decimal TOWID { get; set; }
    }
}
