//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL_RUN_STATUS
    {
        public decimal ID { get; set; }
        public string CHANNEL_NAME { get; set; }
        public string CLIENT_GROUP { get; set; }
        public string PRACTICE { get; set; }
        public Nullable<decimal> DIVISION { get; set; }
        public string RUN_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
    }
}
