//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL_STATISTICS
    {
        public string SERVER_ID { get; set; }
        public string CHANNEL_ID { get; set; }
        public Nullable<decimal> RECEIVED { get; set; }
        public Nullable<decimal> FILTERED { get; set; }
        public Nullable<decimal> SENT { get; set; }
        public Nullable<decimal> ERROR { get; set; }
        public Nullable<decimal> QUEUED { get; set; }
        public Nullable<decimal> ALERTED { get; set; }
    
        public virtual CHANNEL CHANNEL { get; set; }
    }
}
