//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARTMOVER_RUNSTATUS
    {
        public decimal ID { get; set; }
        public string SERVICETYPE { get; set; }
        public Nullable<decimal> CLIENTKEY { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> BATCHID { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
    }
}
