//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG
    {
        public string CF_SEC_NAME { get; set; }
        public string CF_SUB_SEC_NAME { get; set; }
        public string CF_VALUE { get; set; }
    }
}
