//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACTWIZARDLOGGER
    {
        public decimal CONTRACTWIZARDLOGGER_ID { get; set; }
        public string USERID { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string ENCTRNO { get; set; }
        public string INITBY { get; set; }
        public string ORIGIN { get; set; }
        public string DESTIN { get; set; }
        public string ORIGINMOD { get; set; }
        public string DESTMOD { get; set; }
        public string LINEOFBUSINESS { get; set; }
        public string TYPEOFBUSINESS { get; set; }
        public string DOCNO { get; set; }
        public string DOS { get; set; }
        public string UNITNO { get; set; }
        public string AGE { get; set; }
        public string RECEIVETIME { get; set; }
        public string DISPATCHTIME { get; set; }
        public string ENROUTETIME { get; set; }
        public string ONSCENETIME { get; set; }
        public string TRANSPORTTIME { get; set; }
        public string ARRIVALTIME { get; set; }
        public string AVAILABLETIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> NOPAYORS { get; set; }
        public Nullable<decimal> NOQUESTIONS { get; set; }
        public Nullable<decimal> TIMEGAP { get; set; }
        public string POTENCIALLIST { get; set; }
        public string RESULTS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
