//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACTWIZARDQUESTION
    {
        public decimal CONTRACTWIZARDQUESTION_ID { get; set; }
        public decimal CONTRACTWIZARDLOGGER_ID { get; set; }
        public Nullable<decimal> QUESTION { get; set; }
        public string ANSWER { get; set; }
        public string AVAILABLEANSWERS { get; set; }
        public string QUALIFYINGREPLIES { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
