//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURIER_INFO
    {
        public long COURIER_ID { get; set; }
        public long LOG_CONTROL { get; set; }
        public long RESERVED_1 { get; set; }
        public long RESERVED_2 { get; set; }
        public long RESERVED_3 { get; set; }
        public string PLX_RSERVC1 { get; set; }
        public string PLX_RSERVC2 { get; set; }
        public string PLX_RSERVC3 { get; set; }
        public string PLX_RSERVC4 { get; set; }
        public string PLX_RSERVC5 { get; set; }
        public string PLX_RSERVC6 { get; set; }
        public string PLX_RSERVC7 { get; set; }
        public string PLX_RSERVC8 { get; set; }
        public string PLX_RSERVC9 { get; set; }
        public string PLX_RSERVC10 { get; set; }
        public string PLX_RSERVC11 { get; set; }
        public string PLX_RSERVC12 { get; set; }
        public string PLX_RSERVC13 { get; set; }
        public string PLX_RSERVC14 { get; set; }
        public string PLX_RSERVC15 { get; set; }
        public string PLX_RSERVC16 { get; set; }
        public string PLX_RSERVC17 { get; set; }
        public string PLX_RSERVC18 { get; set; }
        public string PLX_RSERVC19 { get; set; }
        public string PLX_RSERVC20 { get; set; }
        public Nullable<long> PLX_RSERVI1 { get; set; }
        public Nullable<long> PLX_RSERVI2 { get; set; }
        public string DESCRIPTION { get; set; }
        public string REFERENCE { get; set; }
        public long TOP_MAP_ID { get; set; }
    }
}
