//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURIER_LOG
    {
        public long TRANSACTION_NO { get; set; }
        public long COURIER_ID { get; set; }
        public long COURIER_INST_ID { get; set; }
        public long NODE_ID { get; set; }
        public long MAP_NAME_ID { get; set; }
        public long ACT_NAME_ID { get; set; }
        public string RETURN_STATE { get; set; }
        public long USER_ID { get; set; }
        public long MACH_ID { get; set; }
        public long IN_ACT_DATE { get; set; }
        public long REQUEST_DATE { get; set; }
        public long RETURN_DATE { get; set; }
        public string ROOT_LOGIN { get; set; }
        public string USER_TAG { get; set; }
        public string MAP_NAME { get; set; }
        public string ACT_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string MACH_NAME { get; set; }
    }
}
