//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURIER_INSTANCE
    {
        public long COURIER_INST_ID { get; set; }
        public long COURIER_ID { get; set; }
        public long MAP_NAME_ID { get; set; }
        public long ACT_NAME_ID { get; set; }
        public long PRIORITY { get; set; }
        public long STATUS { get; set; }
        public long MAP_ID { get; set; }
        public long PARENT_COURIER { get; set; }
        public long SPLIT_CNT { get; set; }
        public long MAP_INST_ID { get; set; }
        public long NODE_ID { get; set; }
        public long PREV_MAP_INST_ID { get; set; }
        public long PREV_NODE_ID { get; set; }
        public long EVENT_CODE { get; set; }
        public long RENDEZVOUS_NODE_ID { get; set; }
        public long USER_ID { get; set; }
        public long LOGIN_HANDLE { get; set; }
        public long CREATE_DATE { get; set; }
        public long REQUEST_DATE { get; set; }
        public long IN_ACT_DATE { get; set; }
        public long PRIORITY_INCREMENT { get; set; }
        public string RETURN_STATE { get; set; }
        public long ACT_ID { get; set; }
        public long LIST_START_USER { get; set; }
        public long LIST_START_TYPE { get; set; }
        public long LIST_START_USRGRP { get; set; }
        public long LIST_CONT_FLAG { get; set; }
        public string RETURN_VALUE { get; set; }
        public Nullable<decimal> SERV_ID { get; set; }
    }
}
