//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURIER_RELOCATE
    {
        public decimal COURIER_RELOCATE_ID { get; set; }
        public string MAPNAME { get; set; }
        public string FROMACTIVITY { get; set; }
        public string TOACTIVITY { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> ATTEMPTCOUNT { get; set; }
        public Nullable<System.DateTime> COMPLETEDTTM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public Nullable<decimal> COURIERID { get; set; }
        public string ERRMSG { get; set; }
        public string RELOCTYPE { get; set; }
    }
}
