//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRUDRULE
    {
        public string RTITABLE { get; set; }
        public string RTICOLUMN { get; set; }
        public string RTISCHEMA { get; set; }
        public Nullable<decimal> COLUMNMINVALUE { get; set; }
        public Nullable<decimal> COLUMNMAXVALUE { get; set; }
        public string VALIDENTRIES { get; set; }
        public string ISREQUIRED { get; set; }
        public string CANEDIT { get; set; }
        public string ISPRIMARYKEY { get; set; }
        public string COLUMNTYPE { get; set; }
        public string DEFAULTVALUE { get; set; }
        public Nullable<System.DateTime> CREATEDTIMESTAMP { get; set; }
        public Nullable<System.DateTime> MODIFIEDTIMESTAMP { get; set; }
        public string ISCOMBOBOXCOLUMN { get; set; }
        public string DBNAME { get; set; }
    }
}
