//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMIZESEGMENT
    {
        public decimal CUSTOMIZESEGMENTS_ID { get; set; }
        public Nullable<decimal> ETL_CONFIG_ID { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string ADTCOLUMN { get; set; }
        public string CODE { get; set; }
        public string EMBILLZCODE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ETL_CONFIG ETL_CONFIG { get; set; }
    }
}
