//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEADLINE_CONFIG
    {
        public long SERV_ID { get; set; }
        public long DDLN_ON { get; set; }
        public long CURR_DDLN { get; set; }
        public long PRIORITY_INC { get; set; }
        public long MAX_PRIORITY { get; set; }
        public long DEF_PORT_NUM { get; set; }
    }
}
