//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEADLINE
    {
        public Nullable<long> DEADLINE_ID { get; set; }
        public long COURIER_ID { get; set; }
        public long DEADLINE1 { get; set; }
        public long DEADLINE_ACTION { get; set; }
        public long PRIORITY_INCREMENT { get; set; }
        public long ACTION_COMPLETED { get; set; }
        public string DEADLINE_CMD { get; set; }
        public string DEADLINE_STRING { get; set; }
    }
}
