//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCDETAIL_LOOKUP
    {
        public Nullable<decimal> DOCDETAIL_LOOKUP_ID { get; set; }
        public string DOCDET { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal DOCTYPE_LOOKUP_ID { get; set; }
        public string EXCLUDE_PREPPING { get; set; }
    }
}
