//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSCAN_BATCH
    {
        public decimal EMSCAN_BATCH_ID { get; set; }
        public string ROSTER_NO { get; set; }
        public Nullable<decimal> EMSCAN_STATION_ID { get; set; }
        public Nullable<decimal> EMSCAN_SITE_ID { get; set; }
        public Nullable<decimal> ROSTER_TYPE { get; set; }
        public Nullable<decimal> ROSTER_TOTAL { get; set; }
        public Nullable<decimal> PCR_TOTAL { get; set; }
        public Nullable<decimal> MISSING_TOTAL { get; set; }
        public Nullable<decimal> NONBILL_TOTAL { get; set; }
        public decimal PROCESS_STATUS { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public Nullable<decimal> PROCESSED_TOTAL { get; set; }
        public string SERVICE_NAME { get; set; }
        public string HOST_NAME { get; set; }
        public decimal BATCH_PRIORITY { get; set; }
    }
}
