//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_MSG
    {
        public long LANG_ID { get; set; }
        public long ERR_ID { get; set; }
        public long MSG_TYPE { get; set; }
        public string ERR_MSG { get; set; }
    }
}
