//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETL_CONFIG
    {
        public ETL_CONFIG()
        {
            this.CUSTOMIZESEGMENTS = new HashSet<CUSTOMIZESEGMENT>();
            this.FILTERHL7 = new HashSet<FILTERHL7>();
        }
    
        public decimal ETLCONFIG_ID { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EIQ_ENABLED { get; set; }
    
        public virtual ICollection<CUSTOMIZESEGMENT> CUSTOMIZESEGMENTS { get; set; }
        public virtual ICollection<FILTERHL7> FILTERHL7 { get; set; }
    }
}
