//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETLDRIVER
    {
        public decimal ETLDRIVER_ID { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string STATUS { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string NEWPATIENT { get; set; }
        public Nullable<System.DateTime> EREGIDATE { get; set; }
        public Nullable<System.DateTime> CMSDATE { get; set; }
        public Nullable<System.DateTime> EIQDATE { get; set; }
    }
}
