//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_LOG_CONFIG
    {
        public long SERV_ID { get; set; }
        public long LOG_LEVEL { get; set; }
        public long COUNTRY_CODE { get; set; }
        public long DISK_LOG_CAP { get; set; }
        public string DEBUG_FILE { get; set; }
        public string LOG_FILE { get; set; }
        public long DEF_PORT_NUM { get; set; }
    }
}
