//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILTERHL7
    {
        public decimal FILTER_ID { get; set; }
        public Nullable<decimal> HL7_CONFIG_ID { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string FILTERKEY { get; set; }
        public string FILTERVALUE { get; set; }
        public Nullable<decimal> EXCLUDEVALUE { get; set; }
        public string PV1_3_FILTERVALUE { get; set; }
    
        public virtual ETL_CONFIG ETL_CONFIG { get; set; }
    }
}
