//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLDINFO
    {
        public string TAB { get; set; }
        public string FLD { get; set; }
        public string SYN { get; set; }
        public decimal TYPE { get; set; }
        public decimal LEN { get; set; }
    }
}
