//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBL
    {
        public string TNAME { get; set; }
        public string ANAME { get; set; }
        public Nullable<decimal> FNUM { get; set; }
        public Nullable<decimal> FTYPE { get; set; }
        public string FDATA { get; set; }
        public Nullable<decimal> FROW { get; set; }
        public Nullable<decimal> COL { get; set; }
        public Nullable<decimal> LEN { get; set; }
        public Nullable<decimal> IOTYPE { get; set; }
        public string PIC { get; set; }
        public Nullable<decimal> CONV { get; set; }
        public string VALIDFN { get; set; }
        public string DFLTVAL { get; set; }
        public decimal TOWID { get; set; }
    }
}
