//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWSYS_SERVICES
    {
        public long SERV_ID { get; set; }
        public long HOST_ID { get; set; }
        public long SERV_PID { get; set; }
        public long SERV_TYPE { get; set; }
        public long DOMAIN_ID { get; set; }
        public long STATE { get; set; }
        public long NEXT_STATE { get; set; }
        public long NEXT_STATE_TIME { get; set; }
        public long CMD { get; set; }
        public long CMD_TIME { get; set; }
        public long STATUS { get; set; }
        public long PERSISTENCE { get; set; }
        public long ACT_NAME_ID { get; set; }
        public decimal R_PID { get; set; }
    }
}
