//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWSYS_HOSTS
    {
        public long HOST_ID { get; set; }
        public string HOST_NAME { get; set; }
        public string IP_ADDR { get; set; }
        public long ACTIVE_FLAG { get; set; }
        public string BIN_PATH { get; set; }
        public string DISP_DEV { get; set; }
        public string MIFAM_NAME { get; set; }
        public long MAX_EXEC_RESP_TIME { get; set; }
        public long MAX_SHUT_RESP_TIME { get; set; }
        public long MAX_RESP_TIME { get; set; }
        public long PWD_AUTH_TYPE { get; set; }
        public string PWD_AUTH_FILE { get; set; }
    }
}
