//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWSYS_PROC_CONFIG
    {
        public long HOST_ID { get; set; }
        public string HOST_NAME { get; set; }
        public string PROC_NAME { get; set; }
        public string SYSMON_HOST { get; set; }
        public string LOG_FILE { get; set; }
    }
}
