//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCA_CONVERSION_REF
    {
        public decimal ID { get; set; }
        public string HCACODE { get; set; }
        public Nullable<System.DateTime> DOS_CUTOFF { get; set; }
        public string ISACTIVE { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string CLIENTID { get; set; }
        public string NEW_PRACTICE { get; set; }
        public string NEW_DIVISION { get; set; }
        public string NEW_CLIENTID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string ADTFILE_FORMAT { get; set; }
        public string FILENAME_KEYWORD { get; set; }
        public string CLIENTGROUP { get; set; }
    }
}
