//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCA_GED_INDICATOR
    {
        public decimal ID { get; set; }
        public decimal CLIENTID { get; set; }
        public string HCACODE { get; set; }
        public string ISMAJOR { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string GED_INDICATOR { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
