//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCA_MISSING_RUN
    {
        public decimal HCA_MISSING_RUN_ID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public string STATUS { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> NUMOFFILEMOVED { get; set; }
    }
}
