//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_FILELOAD
    {
        public decimal HL7_FILELOAD_ID { get; set; }
        public string FILENAME { get; set; }
        public Nullable<decimal> FACILITYCODE { get; set; }
        public Nullable<decimal> TOTALHL7MSGRCVD { get; set; }
        public Nullable<decimal> TOTALHL7MSGPRCD { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public Nullable<decimal> TOTALHL7BYTES { get; set; }
        public Nullable<decimal> BYTESREAD { get; set; }
    }
}
