//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_MSGINFO
    {
        public decimal HL7_MSGINFO_ID { get; set; }
        public string MSGCNTRLID { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string DOCTYPE { get; set; }
        public string HL7SEGMENT { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public Nullable<decimal> FILENAMELOADID { get; set; }
        public Nullable<decimal> FACILITYCODE { get; set; }
        public string FILEMODIFYOPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public Nullable<decimal> ISFILECREATED { get; set; }
        public string SEGCONTENTTYPE { get; set; }
        public string RTITYPE { get; set; }
    }
}
