//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_EDLOG
    {
        public decimal ID { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string PLASTNAME { get; set; }
        public string PFIRSTNAME { get; set; }
        public string PMIDDLENAME { get; set; }
        public string DEPOSITION { get; set; }
        public string MISSCODE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string CLIENTCODE { get; set; }
    }
}
