//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_ATTRIBUTES
    {
        public decimal HL7_ATTRIBUTES_ID { get; set; }
        public string SEGMENT { get; set; }
        public decimal SEQ { get; set; }
        public string DT { get; set; }
        public decimal LEN { get; set; }
        public string OPT { get; set; }
        public string RP { get; set; }
        public string TBL { get; set; }
        public string ITEM { get; set; }
        public string ELEMENT_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
