//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_HCA_CHART_FILTER
    {
        public decimal HL7_HCA_FILTER_ID { get; set; }
        public decimal CLIENTID { get; set; }
        public Nullable<decimal> AMCUTOFFPAGE { get; set; }
        public Nullable<decimal> ALCUTOFFPAGE { get; set; }
        public Nullable<decimal> AKCUTOFFPAGE { get; set; }
        public Nullable<decimal> OTCUTOFFPAGE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
