//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_EREGI_ACCTCODE
    {
        public decimal HL7_EREGI_ACCTCODE_ID { get; set; }
        public string ACCTNO { get; set; }
        public string DIVIIND { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> CLIENTCODE { get; set; }
        public string DIV { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PRACTICE { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
    }
}
