//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IfamModelContainer : DbContext
    {
        public IfamModelContainer()
            : base("name=IfamModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACT_RETURN_STATES> ACT_RETURN_STATES { get; set; }
        public DbSet<ACTGRP_NAMES> ACTGRP_NAMES { get; set; }
        public DbSet<ACTIVITY_NAMES> ACTIVITY_NAMES { get; set; }
        public DbSet<ACTV_ACT_CONFIG> ACTV_ACT_CONFIG { get; set; }
        public DbSet<CLAUS> CLAUSES { get; set; }
        public DbSet<COUR_WAIT_CONFIG> COUR_WAIT_CONFIG { get; set; }
        public DbSet<COURIER_INFO> COURIER_INFO { get; set; }
        public DbSet<COURIER_INSTANCE> COURIER_INSTANCE { get; set; }
        public DbSet<COURIER_LOG> COURIER_LOG { get; set; }
        public DbSet<DEADLINE_CONFIG> DEADLINE_CONFIG { get; set; }
        public DbSet<EVENT_LOG_CONFIG> EVENT_LOG_CONFIG { get; set; }
        public DbSet<FWSYS_CONFIG> FWSYS_CONFIG { get; set; }
        public DbSet<FWSYS_HOSTS> FWSYS_HOSTS { get; set; }
        public DbSet<FWSYS_SERVICES> FWSYS_SERVICES { get; set; }
        public DbSet<HIST_CONFIG> HIST_CONFIG { get; set; }
        public DbSet<IFAM_CONFIG> IFAM_CONFIG { get; set; }
        public DbSet<LDAP_CONFIG> LDAP_CONFIG { get; set; }
        public DbSet<LOGIN> LOGINs { get; set; }
        public DbSet<MACHINE_DATA> MACHINE_DATA { get; set; }
        public DbSet<MAP> MAPs { get; set; }
        public DbSet<MAP_ACT> MAP_ACT { get; set; }
        public DbSet<MAP_INSTANCES> MAP_INSTANCES { get; set; }
        public DbSet<MAP_NAMES> MAP_NAMES { get; set; }
        public DbSet<NODE> NODEs { get; set; }
        public DbSet<SERIAL_CONFIG> SERIAL_CONFIG { get; set; }
        public DbSet<SERIAL_IDS> SERIAL_IDS { get; set; }
        public DbSet<STAT_CONFIG> STAT_CONFIG { get; set; }
        public DbSet<TABLE_INFO> TABLE_INFO { get; set; }
        public DbSet<USER_GROUP_NAMES> USER_GROUP_NAMES { get; set; }
        public DbSet<USER> USERS { get; set; }
        public DbSet<VARIABLE> VARIABLES { get; set; }
        public DbSet<ACTGRP_FORWARD> ACTGRP_FORWARD { get; set; }
        public DbSet<ACTGRP_PERM_HOLD> ACTGRP_PERM_HOLD { get; set; }
        public DbSet<ACTGRP_PERMISSION> ACTGRP_PERMISSION { get; set; }
        public DbSet<CONFIG> CONFIGs { get; set; }
        public DbSet<DBVERSION> DBVERSIONs { get; set; }
        public DbSet<DEADLINE> DEADLINEs { get; set; }
        public DbSet<DEF_PERM_HOLD> DEF_PERM_HOLD { get; set; }
        public DbSet<ERROR_MSG> ERROR_MSG { get; set; }
        public DbSet<FLOW_STAT> FLOW_STAT { get; set; }
        public DbSet<FWSYS_PROC_CONFIG> FWSYS_PROC_CONFIG { get; set; }
        public DbSet<MAP_ACT_INST> MAP_ACT_INST { get; set; }
        public DbSet<MAP_DATA> MAP_DATA { get; set; }
        public DbSet<PERMISSION> PERMISSIONs { get; set; }
        public DbSet<PERMISSION_HOLD> PERMISSION_HOLD { get; set; }
        public DbSet<PLX_ACCESS_ALLOW> PLX_ACCESS_ALLOW { get; set; }
        public DbSet<PLX_ACCESS_DENY> PLX_ACCESS_DENY { get; set; }
        public DbSet<ROUTE> ROUTEs { get; set; }
        public DbSet<RTI_STATUS> RTI_STATUS { get; set; }
        public DbSet<RULE_CONTROL> RULE_CONTROL { get; set; }
        public DbSet<SPLIT> SPLITs { get; set; }
        public DbSet<USER_GROUPS> USER_GROUPS { get; set; }
        public DbSet<WF_CHAR128> WF_CHAR128 { get; set; }
        public DbSet<WF_CURRENCY> WF_CURRENCY { get; set; }
        public DbSet<WF_DATETIME> WF_DATETIME { get; set; }
        public DbSet<WF_FLOAT64> WF_FLOAT64 { get; set; }
        public DbSet<WF_INT32> WF_INT32 { get; set; }
    }
}
