//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFAM_CONFIG
    {
        public long SERV_ID { get; set; }
        public long IFAM_TYPE { get; set; }
        public long CIFAM_CNT { get; set; }
        public long USER_CNT { get; set; }
        public long CRR_LOG_FLAG { get; set; }
        public long LOG_HANDLE_BASE { get; set; }
        public long DATALIST_SEC_CHK { get; set; }
        public string TRACE_FILE { get; set; }
        public long MAX_RUN_TIME { get; set; }
        public long CURRENCY_PREC { get; set; }
        public long MORE_ROWS_FLAG { get; set; }
        public long DEF_PORT_NUM { get; set; }
        public long COMP_UPD_FLAG { get; set; }
    }
}
