//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_DFT_DTL
    {
        public decimal IMPORT_DFT_DTL_ID { get; set; }
        public decimal IMPORT_DFT_HDR_ID { get; set; }
        public string STATUS { get; set; }
        public string TRANS_UID { get; set; }
        public string OP_PROC_NO { get; set; }
        public string OP_PROC_DESC { get; set; }
        public string FTMOD { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> TRANSDT { get; set; }
        public string DIAG_CODE { get; set; }
        public string PROV_NAME { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public string PROC_ERRMSG { get; set; }
        public Nullable<decimal> CLAIM { get; set; }
    
        public virtual IMPORT_DFT_HDR IMPORT_DFT_HDR { get; set; }
    }
}
