//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_ACC_DTL
    {
        public decimal IMPORT_ACC_DTL_ID { get; set; }
        public decimal IMPORT_DFT_HDR_ID { get; set; }
        public Nullable<System.DateTime> ACC_DATE { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_LOCATION { get; set; }
        public string ACC_STATE { get; set; }
        public string ACC_JOB_INDICATOR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    
        public virtual IMPORT_DFT_HDR IMPORT_DFT_HDR { get; set; }
    }
}
