//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_LOGFILE
    {
        public decimal LOGFILE_ID { get; set; }
        public string HOSP_CODE { get; set; }
        public string HOSP_NAME { get; set; }
        public string CPT { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string MED_REC_NO { get; set; }
        public string ACCT_NO { get; set; }
        public string PATIENT_LNAME { get; set; }
        public string PATIENT_FNAME { get; set; }
        public string PHYSYCIAN_LNAME { get; set; }
        public Nullable<System.DateTime> BATCH_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public string LOGFILENAME { get; set; }
    }
}
