//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDAP_CONFIG
    {
        public long SERV_ID { get; set; }
        public string DEF_AUTH { get; set; }
        public string HOST_NAME { get; set; }
        public Nullable<long> PORT_NUM { get; set; }
        public string SCOPE { get; set; }
        public string BASE { get; set; }
        public string SEARCH_FILT { get; set; }
    }
}
