//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public long LOGIN_HANDLE { get; set; }
        public long USER_ID { get; set; }
        public long MAP_NAME_ID { get; set; }
        public long ACT_NAME_ID { get; set; }
        public long MACH_ID { get; set; }
        public long LOGIN_TIME { get; set; }
        public long SERV_ID { get; set; }
        public Nullable<long> TIME_STAMP { get; set; }
    }
}
