//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_INSTANCES
    {
        public long MAP_INST_ID { get; set; }
        public long MAP_ID { get; set; }
        public long PARENT_MAP_ID { get; set; }
        public long PARENT_NODE_ID { get; set; }
        public long PARENT_MAP_INST_ID { get; set; }
        public long TOP_MAP_NAME_ID { get; set; }
    }
}
