//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ACT
    {
        public long ACT_ID { get; set; }
        public long ACT_NAME_ID { get; set; }
        public long MAP_NAME_ID { get; set; }
        public long ACT_STATUS { get; set; }
        public long PRIORITY { get; set; }
        public long ACT_ATTR { get; set; }
    }
}
