//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_NAMES
    {
        public long MAP_NAME_ID { get; set; }
        public string MAP_NAME { get; set; }
        public long MAP_LOGIN { get; set; }
        public long LATEST_VERSION { get; set; }
        public long RETAIN_FLAG { get; set; }
        public long FW { get; set; }
        public long COMMIT_LH { get; set; }
    }
}
