//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_DATA
    {
        public long MAP_ID { get; set; }
        public long MAP_DATA_TYPE { get; set; }
        public long MAP_DATA_SIZE { get; set; }
        public long TIME_STAMP { get; set; }
        public long LOCK_FLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public byte[] MAP_DATA_BLOB { get; set; }
    }
}
