//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public decimal SEQUENCE_ID { get; set; }
        public string ID { get; set; }
        public string SERVER_ID { get; set; }
        public string CHANNEL_ID { get; set; }
        public string SOURCE { get; set; }
        public string TYPE { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public string VERSION { get; set; }
        public string IS_ENCRYPTED { get; set; }
        public string STATUS { get; set; }
        public string RAW_DATA { get; set; }
        public string RAW_DATA_PROTOCOL { get; set; }
        public string TRANSFORMED_DATA { get; set; }
        public string TRANSFORMED_DATA_PROTOCOL { get; set; }
        public string ENCODED_DATA { get; set; }
        public string ENCODED_DATA_PROTOCOL { get; set; }
        public string CONNECTOR_MAP { get; set; }
        public string CHANNEL_MAP { get; set; }
        public string RESPONSE_MAP { get; set; }
        public string CONNECTOR_NAME { get; set; }
        public string ERRORS { get; set; }
        public string CORRELATION_ID { get; set; }
        public Nullable<decimal> ATTACHMENT { get; set; }
    
        public virtual CHANNEL CHANNEL { get; set; }
    }
}
