//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NODE
    {
        public long NODE_ID { get; set; }
        public long NODE_TYPE { get; set; }
        public long LINK_ID { get; set; }
        public long MAP_ID { get; set; }
        public long USER_NODE_ID { get; set; }
    }
}
