//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODS_HL7MSG
    {
        public decimal ODSMSH_ID { get; set; }
        public string FIELDSEPARATOR { get; set; }
        public string ENCODINGCHARACTERS { get; set; }
        public string SENDINGAPPLICATION { get; set; }
        public string SENDINGFACILITY { get; set; }
        public string RECEIVINGAPPLICATION { get; set; }
        public string RECEIVINGFACILITY { get; set; }
        public Nullable<System.DateTime> MESSAGEDATETIME { get; set; }
        public string MESSAGETYPE { get; set; }
        public string MESSAGECONTROLID { get; set; }
        public string PROCESSINGID { get; set; }
        public string VERSIONID { get; set; }
        public string EVENTTYPECODE { get; set; }
        public Nullable<System.DateTime> EVENTRECORDEDDATETIME { get; set; }
        public Nullable<System.DateTime> CREATETIMESTAMP { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public decimal ODSPID_ID { get; set; }
        public Nullable<decimal> SETID { get; set; }
        public string EXTERNALID_MRN { get; set; }
        public string INTERNALID { get; set; }
        public string PAT_LASTNAME { get; set; }
        public string PAT_FIRSTNAME { get; set; }
        public string PAT_MIDDLENAME { get; set; }
        public Nullable<System.DateTime> PAT_DATEOFBIRTH { get; set; }
        public string PAT_SEX { get; set; }
        public string PAT_RACE { get; set; }
        public string PAT_ADDRESS1 { get; set; }
        public string PAT_ADDRESS2 { get; set; }
        public string PAT_CITY { get; set; }
        public string PAT_STATE { get; set; }
        public string PAT_ZIP { get; set; }
        public string PAT_HOMEPHONE { get; set; }
        public string PAT_BUSINESSPHONE { get; set; }
        public string PAT_MARITALSTATUSCODE { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string PAT_SSN { get; set; }
        public string PCPINFORMATION { get; set; }
        public Nullable<short> PAT_STUDENTINDICATOR { get; set; }
        public string CHECKDIGIT { get; set; }
        public Nullable<decimal> ODSPV1_ID { get; set; }
        public string PATIENTCLASS { get; set; }
        public string ASSIGNEDPATIENTLOCATION { get; set; }
        public string ATTENDINGDOCTORID { get; set; }
        public string ATTENDINGDOCTORNAME { get; set; }
        public string REFERRINGDOCTORID { get; set; }
        public string REFERRINGDOCTORNAME { get; set; }
        public string PATIENTTYPE { get; set; }
        public string VISITNUMBER { get; set; }
        public string FINANCIALCLASS { get; set; }
        public string DISCHARGEDISPOSITION { get; set; }
        public string DISCHARGETOLOCATION { get; set; }
        public Nullable<System.DateTime> ADMITDATETIME { get; set; }
        public Nullable<System.DateTime> DISCHARGEDATETIME { get; set; }
        public string CHIEFCOMPLAINT { get; set; }
        public Nullable<System.DateTime> PREVIOUSADMITDATE { get; set; }
        public string MODEOFARRIVAL { get; set; }
        public string CASEUSERDATA { get; set; }
        public string GROUPNO { get; set; }
        public string POLICYNO { get; set; }
        public string GROUPNO2 { get; set; }
        public string POLICYNO2 { get; set; }
        public string ADMITPATIENTCLASS { get; set; }
        public Nullable<decimal> ODSEVN_ID { get; set; }
        public string EVENTTYPECODE2 { get; set; }
        public Nullable<System.DateTime> EVENTDATETIME { get; set; }
        public string OPERATORID { get; set; }
        public Nullable<decimal> ODSGT1_ID { get; set; }
        public string GUARANTORNUMBER { get; set; }
        public string GUARANTORLASTNAME { get; set; }
        public string GUARANTORFIRSTNAME { get; set; }
        public string GUARANTORMIDDLENAME { get; set; }
        public string GUARANTORADDRESS1 { get; set; }
        public string GUARANTORADDRESS2 { get; set; }
        public string GUARANTORCITY { get; set; }
        public string GUARANTORSTATE { get; set; }
        public string GUARANTORZIP { get; set; }
        public string GUARANTORHOMEPHONE { get; set; }
        public string GUARANTORBUSINESSPHONE { get; set; }
        public Nullable<System.DateTime> GUARANTORDATEOFBIRTH { get; set; }
        public string GUARANTORSEX { get; set; }
        public string GUARANTORRELATIONSHIP { get; set; }
        public string GUARANTORSSN { get; set; }
        public string GUARANTOREMPLOYERNAME { get; set; }
        public string GUARANTOREMPLOYERADDRESS1 { get; set; }
        public string GUARANTOREMPLOYERADDRESS2 { get; set; }
        public string GUARANTOREMPLOYERCITY { get; set; }
        public string GUARANTOREMPLOYERSTATE { get; set; }
        public string GUARANTOREMPLOYERZIP { get; set; }
        public string GUARANTOREMPLOYERPHONE { get; set; }
        public Nullable<decimal> ODSNK1_ID { get; set; }
        public string NK_LASTNAME { get; set; }
        public string NK_FIRSTNAME { get; set; }
        public string NK_MIDDLENAME { get; set; }
        public string RELATIONSHIP { get; set; }
        public string NK_ADDRESS1 { get; set; }
        public string NK_ADDRESS2 { get; set; }
        public string NK_CITY { get; set; }
        public string NK_STATE { get; set; }
        public string NK_ZIP { get; set; }
        public string NK_PHONE { get; set; }
        public string NK_BUSINESSPHONE { get; set; }
        public string NK_MARITALSTATUSCODE { get; set; }
        public string NK_SEX { get; set; }
        public Nullable<System.DateTime> NK_DATEOFBIRTH { get; set; }
        public Nullable<decimal> ODSIN1_ID { get; set; }
        public Nullable<decimal> INSURANCESETID { get; set; }
        public string INSURANCEPLANID { get; set; }
        public string INSURANCEID { get; set; }
        public string INSURANCENAME { get; set; }
        public string INSURANCEADDRESS1 { get; set; }
        public string INSURANCEADDRESS2 { get; set; }
        public string INSURANCECITY { get; set; }
        public string INSURANCESTATE { get; set; }
        public string INSURANCEZIP { get; set; }
        public string INSURANCECONTACT { get; set; }
        public string INSURANCEPHONENUMBER { get; set; }
        public string GROUPNUMBER { get; set; }
        public string GROUPNAME { get; set; }
        public string INSUREDGROUPEMPID { get; set; }
        public string INSUREDGROUPEMPNAME { get; set; }
        public Nullable<System.DateTime> PLANEFFECTIVEDATE { get; set; }
        public Nullable<System.DateTime> PLANEXPIRATIONDATE { get; set; }
        public string AUTHORIZATIONINFORMATION { get; set; }
        public string PLANTYPE { get; set; }
        public string INSUREDLASTNAME { get; set; }
        public string INSUREDFIRSTNAME { get; set; }
        public string INSUREDRELATIONSHIP { get; set; }
        public Nullable<System.DateTime> INSUREDDATEOFBIRTH { get; set; }
        public string INSUREDADDRESS1 { get; set; }
        public string INSUREDADDRESS2 { get; set; }
        public string INSUREDCITY { get; set; }
        public string INSUREDSTATE { get; set; }
        public string INSUREDZIP { get; set; }
        public string PREADMITCERT { get; set; }
        public string COMPANYPLANCODE { get; set; }
        public string POLICYNUMBER { get; set; }
        public string INSUREDSEX { get; set; }
        public string INSUREDEMPLOYERADDRESS1 { get; set; }
        public string INSUREDEMPLOYERADDRESS2 { get; set; }
        public string INSUREDEMPLOYERCITY { get; set; }
        public string INSUREDEMPLOYERSTATE { get; set; }
        public string INSUREDEMPLOYERZIP { get; set; }
        public string INSUREDIDNUMBER { get; set; }
        public string INSUREDSSN { get; set; }
        public string INSUREDEMPLOYERNAME { get; set; }
        public string INSUREDHOMEPHONE { get; set; }
        public string INSUREDWORKPHONE { get; set; }
        public string INSUREDMIDDLENAME { get; set; }
        public Nullable<System.DateTime> ACC_ACTIVITYTIME { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_LOCATION { get; set; }
        public string ACC_ACCIDENTSTATE { get; set; }
        public string ACC_JOBRELATED { get; set; }
        public string ACC_MODELDEADLY { get; set; }
        public string ACC_MODELENTEREDBY { get; set; }
    }
}
