//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSGT1
    {
        public decimal ODSGT1_ID { get; set; }
        public decimal ODSPID_ID { get; set; }
        public Nullable<decimal> SETID { get; set; }
        public string GUARANTORNUMBER { get; set; }
        public string GUARANTORLASTNAME { get; set; }
        public string GUARANTORFIRSTNAME { get; set; }
        public string GUARANTORMIDDLENAME { get; set; }
        public string GUARANTORADDRESS1 { get; set; }
        public string GUARANTORADDRESS2 { get; set; }
        public string GUARANTORCITY { get; set; }
        public string GUARANTORSTATE { get; set; }
        public string GUARANTORZIP { get; set; }
        public string GUARANTORHOMEPHONE { get; set; }
        public string GUARANTORBUSINESSPHONE { get; set; }
        public Nullable<System.DateTime> GUARANTORDATEOFBIRTH { get; set; }
        public string GUARANTORSEX { get; set; }
        public string GUARANTORRELATIONSHIP { get; set; }
        public string GUARANTORSSN { get; set; }
        public string GUARANTOREMPLOYERNAME { get; set; }
        public string GUARANTOREMPLOYERADDRESS1 { get; set; }
        public string GUARANTOREMPLOYERADDRESS2 { get; set; }
        public string GUARANTOREMPLOYERCITY { get; set; }
        public string GUARANTOREMPLOYERSTATE { get; set; }
        public string GUARANTOREMPLOYERZIP { get; set; }
        public string GUARANTOREMPLOYERPHONE { get; set; }
        public string GTRCOUNTRY { get; set; }
    }
}
