//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSIN1
    {
        public decimal ODSIN1_ID { get; set; }
        public decimal ODSPID_ID { get; set; }
        public Nullable<decimal> SETID { get; set; }
        public string INSURANCEPLANID { get; set; }
        public string INSURANCEID { get; set; }
        public string INSURANCENAME { get; set; }
        public string INSURANCEADDRESS1 { get; set; }
        public string INSURANCEADDRESS2 { get; set; }
        public string INSURANCECITY { get; set; }
        public string INSURANCESTATE { get; set; }
        public string INSURANCEZIP { get; set; }
        public string INSURANCECONTACT { get; set; }
        public string INSURANCEPHONENUMBER { get; set; }
        public string GROUPNUMBER { get; set; }
        public string GROUPNAME { get; set; }
        public string INSUREDGROUPEMPID { get; set; }
        public string INSUREDGROUPEMPNAME { get; set; }
        public Nullable<System.DateTime> PLANEFFECTIVEDATE { get; set; }
        public Nullable<System.DateTime> PLANEXPIRATIONDATE { get; set; }
        public string AUTHORIZATIONINFORMATION { get; set; }
        public string PLANTYPE { get; set; }
        public string INSUREDLASTNAME { get; set; }
        public string INSUREDFIRSTNAME { get; set; }
        public string INSUREDRELATIONSHIP { get; set; }
        public Nullable<System.DateTime> INSUREDDATEOFBIRTH { get; set; }
        public string INSUREDADDRESS1 { get; set; }
        public string INSUREDADDRESS2 { get; set; }
        public string INSUREDCITY { get; set; }
        public string INSUREDSTATE { get; set; }
        public string INSUREDZIP { get; set; }
        public string PREADMITCERT { get; set; }
        public string COMPANYPLANCODE { get; set; }
        public string POLICYNUMBER { get; set; }
        public string INSUREDSEX { get; set; }
        public string INSUREDEMPLOYERADDRESS1 { get; set; }
        public string INSUREDEMPLOYERADDRESS2 { get; set; }
        public string INSUREDEMPLOYERCITY { get; set; }
        public string INSUREDEMPLOYERSTATE { get; set; }
        public string INSUREDEMPLOYERZIP { get; set; }
        public string INSUREDIDNUMBER { get; set; }
        public string INSUREDSSN { get; set; }
        public string INSUREDEMPLOYERNAME { get; set; }
        public string INSUREDHOMEPHONE { get; set; }
        public string INSUREDWORKPHONE { get; set; }
        public string INSUREDMIDDLENAME { get; set; }
        public string PAYORID { get; set; }
        public string INSCOUNTRY { get; set; }
        public string INSUREDCOUNTRY { get; set; }
        public string MEDICAREHEALTHINSID { get; set; }
    }
}
