//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSPV1
    {
        public decimal ODSPV1_ID { get; set; }
        public decimal ODSPID_ID { get; set; }
        public Nullable<decimal> SETID { get; set; }
        public string PATIENTCLASS { get; set; }
        public string ASSIGNEDPATIENTLOCATION { get; set; }
        public string ATTENDINGDOCTORID { get; set; }
        public string ATTENDINGDOCTORNAME { get; set; }
        public string REFERRINGDOCTORID { get; set; }
        public string REFERRINGDOCTORNAME { get; set; }
        public string PATIENTTYPE { get; set; }
        public string VISITNUMBER { get; set; }
        public string FINANCIALCLASS { get; set; }
        public string DISCHARGEDISPOSITION { get; set; }
        public string DISCHARGETOLOCATION { get; set; }
        public Nullable<System.DateTime> ADMITDATETIME { get; set; }
        public Nullable<System.DateTime> DISCHARGEDATETIME { get; set; }
        public string CHIEFCOMPLAINT { get; set; }
        public Nullable<System.DateTime> PREVIOUSADMITDATE { get; set; }
        public string MODEOFARRIVAL { get; set; }
        public string CASEUSERDATA { get; set; }
        public string GROUPNO { get; set; }
        public string POLICYNO { get; set; }
        public string GROUPNO2 { get; set; }
        public string POLICYNO2 { get; set; }
        public string ADMITPATIENTCLASS { get; set; }
        public string HOSPITALSERVICE { get; set; }
        public string ALTERNATEVISITID { get; set; }
        public string ADMISSIONTYPE { get; set; }
        public string ORIGINALPATIENTLOCATION { get; set; }
        public string ORIGINALPATIENTCLASS { get; set; }
    }
}
