//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLSQL_PROFILER_UNITS
    {
        public decimal RUNID { get; set; }
        public decimal UNIT_NUMBER { get; set; }
        public string UNIT_TYPE { get; set; }
        public string UNIT_OWNER { get; set; }
        public string UNIT_NAME { get; set; }
        public Nullable<System.DateTime> UNIT_TIMESTAMP { get; set; }
        public Nullable<decimal> TOTAL_TIME { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
    
        public virtual PLSQL_PROFILER_RUNS PLSQL_PROFILER_RUNS { get; set; }
    }
}
