//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLSQL_PROFILER_DATA
    {
        public decimal RUNID { get; set; }
        public decimal UNIT_NUMBER { get; set; }
        public decimal LINE_ { get; set; }
        public Nullable<decimal> TOTAL_OCCUR { get; set; }
        public Nullable<decimal> TOTAL_TIME { get; set; }
        public Nullable<decimal> MIN_TIME { get; set; }
        public Nullable<decimal> MAX_TIME { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> SPARE4 { get; set; }
    }
}
