//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTBDDETAILPOSTDOCVIEW
    {
        public string IFN { get; set; }
        public decimal POSTDETAIL_ID { get; set; }
        public Nullable<decimal> COURIER_INST_ID { get; set; }
        public string PARDOCNO { get; set; }
        public Nullable<decimal> LEFT { get; set; }
        public Nullable<decimal> TOP { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> XSCALE { get; set; }
        public Nullable<decimal> YSCALE { get; set; }
        public Nullable<decimal> ORIENTATION { get; set; }
        public Nullable<decimal> HSCROLL { get; set; }
        public Nullable<decimal> VSCROLL { get; set; }
        public Nullable<decimal> DOCPAGE { get; set; }
        public string INFORMATIONAL { get; set; }
        public decimal ALT_TOWID { get; set; }
        public Nullable<System.DateTime> DEPDT { get; set; }
        public string REASON { get; set; }
    }
}
