//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTDETAIL_NEW
    {
        public decimal POSTDETAIL_ID { get; set; }
        public Nullable<decimal> TOWID { get; set; }
        public Nullable<System.DateTime> SVCDT { get; set; }
        public Nullable<decimal> PAIDAMT { get; set; }
        public string EMBACCT { get; set; }
        public string ROUTEINFO { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> DOCPAGE { get; set; }
        public string MODIFYUID { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string CREATEUID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<decimal> LEFT { get; set; }
        public Nullable<decimal> TOP { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> XSCALE { get; set; }
        public Nullable<decimal> YSCALE { get; set; }
        public Nullable<decimal> ORIENTATION { get; set; }
        public Nullable<decimal> HSCROLL { get; set; }
        public Nullable<decimal> VSCROLL { get; set; }
        public string IFN { get; set; }
        public string NEXT_ACT_NAME { get; set; }
        public string NEXT_MAP_NAME { get; set; }
        public string REASON { get; set; }
        public string INFORMATIONAL { get; set; }
    }
}
