//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTBD
    {
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string DEPDT { get; set; }
        public string RECDATE { get; set; }
        public string WHO { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string DOCNO { get; set; }
        public string PARDOCNO { get; set; }
        public string STATUS { get; set; }
        public string REASON { get; set; }
        public string ACCTNUM { get; set; }
        public string EMBACCT { get; set; }
        public string CHECKNUM { get; set; }
        public string CHECKAMT { get; set; }
        public string PAIDAMT { get; set; }
        public string EXTPAYOR { get; set; }
        public string DEPCODE { get; set; }
        public string DOCGROUP { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCDET { get; set; }
        public Nullable<decimal> COURIER_INST_ID { get; set; }
        public Nullable<decimal> PLX_COURIER_ID { get; set; }
        public string ACT_NAME { get; set; }
        public string MAP_NAME { get; set; }
        public Nullable<decimal> NODE_ID { get; set; }
        public Nullable<decimal> MAP_INST_ID { get; set; }
        public string IFN { get; set; }
        public Nullable<decimal> POSTDETAIL_ID { get; set; }
        public Nullable<decimal> TOWID { get; set; }
        public string USERID { get; set; }
        public string RECEIVEDATE { get; set; }
        public decimal POSTBD_ID { get; set; }
        public string SVCDT { get; set; }
        public string IMPORT_INFO { get; set; }
        public string ROUTEINFO { get; set; }
        public string USERNAME { get; set; }
        public string FINANCIAL_CLASS { get; set; }
        public string ESCALATION_REASON { get; set; }
        public string CORRECTION_FOLDER { get; set; }
        public string INFORMATIONAL { get; set; }
        public string SERVICEID { get; set; }
    }
}
