//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_STATUS_LOOKUP
    {
        public decimal PROCESS_STATUS_LOOKUP_ID { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
