//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_COLLECTION_DEF_REPOS
    {
        public string SAMPLE_SET { get; set; }
        public Nullable<decimal> GENERATION_NBR { get; set; }
        public string GENERATION_NAME { get; set; }
        public string SERVICE_NAME { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<decimal> INTERNAL_USER_ID { get; set; }
        public string RESET_HISTORY { get; set; }
        public string ALREADY_IN_BUF { get; set; }
        public Nullable<decimal> SAMPLING_INTERVAL { get; set; }
        public string SAMPLING_UNIT { get; set; }
        public Nullable<System.DateTime> STARTED { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> SQL_QUOTA { get; set; }
        public Nullable<decimal> SQL_COLLECTED { get; set; }
        public Nullable<decimal> SAMPLES { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> LAST_COLLECTED { get; set; }
        public string ELAPSED { get; set; }
        public Nullable<decimal> IS_ACTIVE { get; set; }
        public Nullable<decimal> JOB { get; set; }
        public Nullable<System.DateTime> START_AT { get; set; }
        public Nullable<System.DateTime> STOP_AT { get; set; }
        public string COLLECTOR_MODE { get; set; }
        public Nullable<decimal> INTERVAL { get; set; }
        public string SCOPE { get; set; }
        public string WHERE_CRITERIA { get; set; }
        public string COLLECTOR_NAME { get; set; }
    }
}
