//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_REPOS_BIND_VALUES
    {
        public string GENERATION_ID { get; set; }
        public decimal SEQ { get; set; }
        public string BIND_NAME { get; set; }
        public Nullable<decimal> BIND_TYPE { get; set; }
        public string BIND_VALUE { get; set; }
    }
}
