//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_REPOSITORY_SQLAREA
    {
        public string SQL_TEXT { get; set; }
        public Nullable<decimal> SHARABLE_MEM { get; set; }
        public Nullable<decimal> PERSISTENT_MEM { get; set; }
        public Nullable<decimal> RUNTIME_MEM { get; set; }
        public Nullable<decimal> SORTS { get; set; }
        public Nullable<decimal> OPEN_IND { get; set; }
        public Nullable<decimal> USERS_OPENING { get; set; }
        public Nullable<decimal> EXECUTIONS { get; set; }
        public Nullable<decimal> USERS_EXECUTING { get; set; }
        public Nullable<decimal> LOADS { get; set; }
        public string FIRST_LOAD_TIME { get; set; }
        public Nullable<decimal> PARSE_CALLS { get; set; }
        public Nullable<decimal> DISK_READS { get; set; }
        public Nullable<decimal> BUFFER_GETS { get; set; }
        public Nullable<decimal> ROWS_PROCESSED { get; set; }
        public Nullable<decimal> COMMAND_TYPE { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<decimal> SCHEMA_ID { get; set; }
        public string ADDRESS { get; set; }
        public string PARENT_ADDRESS { get; set; }
        public Nullable<decimal> HASH_VALUE { get; set; }
        public string USERNAME { get; set; }
        public string SAMPLE_SET { get; set; }
        public Nullable<decimal> SQL_TEXT_LEN { get; set; }
        public string CONNECT_USER { get; set; }
        public string OSUSER { get; set; }
        public string SID { get; set; }
        public string OWNER { get; set; }
        public string OBJECT_NAME { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public string TABLESPACE_NAME { get; set; }
        public string GENERATION_ID { get; set; }
        public Nullable<decimal> LOGICAL_READS { get; set; }
        public Nullable<decimal> PHYSICAL_READS { get; set; }
        public Nullable<decimal> LOGICAL_CHANGES { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public Nullable<decimal> DISK_READS_PER_EXECUTE { get; set; }
        public Nullable<decimal> BUFFER_GETS_PER_EXECUTE { get; set; }
        public Nullable<decimal> ROWS_PROCESSED_PER_EXECUTE { get; set; }
        public string TRANSACTION { get; set; }
        public string APPLICATION { get; set; }
    }
}
