//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_REPOSITORY_TRANS_INFO
    {
        public string TUNING_SESSION { get; set; }
        public decimal SCENARIO_NMBR { get; set; }
        public string SERVER_NAME { get; set; }
        public string INSTANCE_NAME { get; set; }
        public Nullable<decimal> ORACLE_VERSION_NMBR { get; set; }
        public string ORACLE_VERSION_NAME { get; set; }
        public Nullable<decimal> BLOCK_SIZE { get; set; }
        public string USE_SPACER_STATS { get; set; }
        public string USER_NAME { get; set; }
        public string USER_DBA_ROLE { get; set; }
        public Nullable<decimal> INTERNAL_USER_ID { get; set; }
        public string SESSION_AUDIT_ID { get; set; }
        public string HOST { get; set; }
        public string SID { get; set; }
    }
}
