//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_REPOS_ROOT
    {
        public string SAMPLE_SET { get; set; }
        public string SOURCE { get; set; }
        public string ROOT_COMMENT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<decimal> TOTAL_GENERATIONS { get; set; }
        public Nullable<decimal> ACCUM_SQL_COUNT { get; set; }
        public string USERNAME { get; set; }
        public Nullable<decimal> INTERNAL_USER_ID { get; set; }
    }
}
