//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_QUERY_DEF_REPOSITORY
    {
        public string SAMPLE_SET { get; set; }
        public Nullable<decimal> GENERATION_NBR { get; set; }
        public string GENERATION_NAME { get; set; }
        public string SCOPE { get; set; }
        public string WHERE_CRITERIA { get; set; }
        public string SERVICE_NAME { get; set; }
        public string USER_NAME { get; set; }
    }
}
