//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_QUERY_DEFINITIONS
    {
        public string QUERY_NAME { get; set; }
        public string SCOPE { get; set; }
        public string WHERE_CRITERIA { get; set; }
        public string SERVICE_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string EXCLUDE_SYS_USER { get; set; }
    }
}
