//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_REPOS_LAB_DETAILS
    {
        public string SAMPLE_SET { get; set; }
        public decimal SCENARIO_NBR { get; set; }
        public string SCENARIO_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string PLANS { get; set; }
        public string STATS { get; set; }
        public string LAB_COMMENT { get; set; }
    }
}
