//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_SL_REPOS_SGA_STATISTICS
    {
        public string SAMPLE_SET { get; set; }
        public decimal GENERATION_NBR { get; set; }
        public decimal SYNTAX_ID { get; set; }
        public decimal SEQUENCE { get; set; }
        public string GENERATION_NAME { get; set; }
        public Nullable<decimal> HASH_VALUE { get; set; }
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
        public string SQL_STATEMENT { get; set; }
        public Nullable<decimal> SQL_LENGTH { get; set; }
        public string USER_NAME { get; set; }
        public string ACTION { get; set; }
        public string MODULE { get; set; }
        public string STATEMENT_ID { get; set; }
        public Nullable<decimal> CPU_USAGE { get; set; }
        public Nullable<decimal> BUFFER_GETS { get; set; }
        public Nullable<decimal> BUFFER_GETS_PER_EXECUTE { get; set; }
        public Nullable<decimal> DISK_READS { get; set; }
        public Nullable<decimal> DISK_READS_PER_EXECUTE { get; set; }
        public Nullable<decimal> ROWS_PROCESSED { get; set; }
        public Nullable<decimal> ROWS_PROCESSED_PER_EXECUTE { get; set; }
        public Nullable<decimal> EXECUTIONS { get; set; }
        public Nullable<decimal> SORTS { get; set; }
        public Nullable<decimal> LOGON_CURRENT { get; set; }
        public Nullable<decimal> OPENED_CURSORS_CUMULATIVE { get; set; }
        public Nullable<decimal> OPENED_CURSORS_CURRENT { get; set; }
        public Nullable<decimal> USER_COMMITS { get; set; }
        public Nullable<decimal> USER_ROLLBAKS { get; set; }
        public Nullable<decimal> USER_CALLS { get; set; }
        public Nullable<decimal> RECURSIVE_CALLS { get; set; }
        public Nullable<decimal> RECURSIVE_CPU_USAGE { get; set; }
        public Nullable<decimal> SESSION_LOGICAL_READS { get; set; }
        public Nullable<decimal> SESSION_STORED_PROCEDURE_SPACE { get; set; }
        public Nullable<decimal> CPU_USED_BY_SESSION { get; set; }
        public Nullable<decimal> SESSION_UGA_MEMORY { get; set; }
        public Nullable<decimal> SESSION_PGA_MEMORY { get; set; }
        public Nullable<decimal> SQLNET_ROUNDTRIPS_CLIENT { get; set; }
        public Nullable<decimal> BYTES_SENT_SQLNET_CLIENT { get; set; }
        public Nullable<decimal> BYTES_RECEIVED_SQLNET_CLIENT { get; set; }
        public Nullable<decimal> BYTES_SENT_SQLNET_DBLINK { get; set; }
        public Nullable<decimal> BYTES_RECEIVED_SQLNET_DBLINK { get; set; }
        public Nullable<decimal> SQLNET_ROUNDTRIPS_DBLINK { get; set; }
        public Nullable<decimal> REDO_ENTRIES { get; set; }
        public Nullable<decimal> REDO_LOG_SPACE_REQUESTS { get; set; }
        public Nullable<decimal> ENQUEUE_WAITS { get; set; }
        public Nullable<decimal> ENQUEUE_REQUESTS { get; set; }
        public Nullable<decimal> DB_BLOCK_GETS { get; set; }
        public Nullable<decimal> CONSISTENT_GETS { get; set; }
        public Nullable<decimal> PHYSICAL_WRITES { get; set; }
        public Nullable<decimal> DB_BLOCK_CHANGES { get; set; }
        public Nullable<decimal> CONSISTENT_CHANGES { get; set; }
        public Nullable<decimal> TABLE_SCANS_SHORT_TABLES { get; set; }
        public Nullable<decimal> TABLE_SCANS_LONG_TABLES { get; set; }
        public Nullable<decimal> TABLE_SCANS_ROWID_RANGES { get; set; }
        public Nullable<decimal> TABLE_SCANS_CACHE_PARTITIONS { get; set; }
        public Nullable<decimal> TABLE_SCANS_SCANS_DIRECT_READ { get; set; }
        public Nullable<decimal> TABLE_SCANS_SCAN_ROWS_GOTTEN { get; set; }
        public Nullable<decimal> TABLE_SCANS_SCAN_BLOCKS_GOTTEN { get; set; }
        public Nullable<decimal> TABLE_FETCH_BY_ROWID { get; set; }
        public Nullable<decimal> TABLE_FETCH_CONTINUED_ROW { get; set; }
        public Nullable<decimal> CLUSTER_KEY_SCAN_BLOCK_GETS { get; set; }
        public Nullable<decimal> PARSE_TIME_CPU { get; set; }
        public Nullable<decimal> PARSE_TIME_ELAPSED { get; set; }
        public Nullable<decimal> PARSE_COUNT { get; set; }
        public Nullable<decimal> EXECUTE_COUNT { get; set; }
        public Nullable<decimal> SORTS_MEMORY { get; set; }
        public Nullable<decimal> SORTS_DISK { get; set; }
        public Nullable<decimal> SORTS_ROWS { get; set; }
        public Nullable<decimal> SESSION_CURSOR_CACHE_HITS { get; set; }
        public Nullable<decimal> OS_USER_LEVEL_CPU { get; set; }
        public Nullable<decimal> OS_SYSTEM_CALL_CPU { get; set; }
        public Nullable<decimal> OS_OTHER_SYSTEM_TRAP_CPU { get; set; }
        public Nullable<decimal> OS_TEXT_PAGE_FAULT_SLEEP { get; set; }
        public Nullable<decimal> OS_DATA_PAGE_FAULT_SLEEP { get; set; }
        public Nullable<decimal> OS_KERNEL_PAGE_FAULT_SLEEP { get; set; }
        public Nullable<decimal> OS_USER_LOCK_WAIT_SLEEP { get; set; }
        public Nullable<decimal> OS_ALL_OTHER_SLEEP { get; set; }
        public Nullable<decimal> OS_WAIT_CPU { get; set; }
        public Nullable<decimal> OS_MINOR_PAGE_FAULTS { get; set; }
        public Nullable<decimal> OS_MAJOR_PAGE_FAULTS { get; set; }
        public Nullable<decimal> TOTAL_CYCLES { get; set; }
        public Nullable<decimal> INACTIVE { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_RUN { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_READY { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_PAGING { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_WAIT { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_STOP { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_IDLE { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_DEAD { get; set; }
        public Nullable<decimal> ACTIVE_STATUS_SWAP { get; set; }
        public Nullable<decimal> WAIT_STATE_NOWAIT { get; set; }
        public Nullable<decimal> WAIT_STATE_IO { get; set; }
        public Nullable<decimal> WAIT_STATE_NETWORK { get; set; }
        public Nullable<decimal> WAIT_STATE_DBMS_MEMORY { get; set; }
        public Nullable<decimal> WAIT_STATE_DBMS_LATCH { get; set; }
        public Nullable<decimal> WAIT_STATE_DBMS_LOCK { get; set; }
        public Nullable<decimal> WAIT_STATE_OTHER { get; set; }
        public Nullable<decimal> THREAD_ACTIVE { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_RUN { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_READY { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_PAGING { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_WAIT { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_STOP { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_IDLE { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_DEAD { get; set; }
        public Nullable<decimal> THREAD_ACTIVE_STATUS_SWAP { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_NO_WAIT { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_IO { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_NETWORK { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_DBMS_MEMORY { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_DBMS_LATCH { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_DBMS_LOCK { get; set; }
        public Nullable<decimal> THREAD_WAIT_STATE_OTHER { get; set; }
        public Nullable<decimal> STARTED_SESSION_COUNT { get; set; }
        public Nullable<decimal> ENDED_SESSION_COUNT { get; set; }
        public Nullable<decimal> TOTAL_SESSION_COUNT { get; set; }
        public Nullable<decimal> CURRENT_STATUS { get; set; }
        public Nullable<decimal> CURRENT_WAIT_TYPE { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<System.DateTime> ELAPSED_TIME { get; set; }
        public Nullable<decimal> ACTIVE_TIME { get; set; }
    }
}
