//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_STATUS
    {
        public string MAP { get; set; }
        public string ACTIVITY { get; set; }
        public long AVAILABLE { get; set; }
        public int INUSE { get; set; }
        public int FRIED { get; set; }
        public int SUSP { get; set; }
        public int ZOMBIE { get; set; }
        public int WIP { get; set; }
        public int TOTAL { get; set; }
    }
}
