//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_EXCEPTION_CODE
    {
        public decimal RTI_EXCEPTION_CODE_ID { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string EXCEPTION_SOURCE { get; set; }
        public string EXCEPTION_GROUP { get; set; }
        public string EXCEPTION_CODE { get; set; }
        public string EXCEPTION_DESCRIPTION { get; set; }
        public decimal ENTER_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
