//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_ACCTSCENARIO
    {
        public decimal RTI_ACCTSCENARIO_ID { get; set; }
        public decimal RTI_OPTION_GROUP { get; set; }
        public decimal SCENARIOID { get; set; }
        public decimal FILETYPE { get; set; }
        public string OPT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
