//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_MISSING_CODE
    {
        public decimal RTI_MISSING_CODE_ID { get; set; }
        public decimal CLIENTKEY { get; set; }
        public string PRACTICE { get; set; }
        public decimal FILETYPE { get; set; }
        public string MISSING_CODE { get; set; }
        public string MISSING_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public string RTI_ACCT_MASK { get; set; }
        public string ATR_ACCT_MASK { get; set; }
    }
}
