//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_BATCHINFO
    {
        public decimal RTI_BATCHINFO_ID { get; set; }
        public decimal CLIENTKEY { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<decimal> TOTAL_ACCOUNT { get; set; }
        public Nullable<decimal> TOTAL_ADT { get; set; }
        public Nullable<decimal> TOTAL_IBX { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
