//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_OPTIONS
    {
        public decimal RTI_OPTIONS_ID { get; set; }
        public decimal RTI_GROUP { get; set; }
        public string RTI_OPTION { get; set; }
        public decimal RULE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public string STATUS { get; set; }
        public string DEPLOY { get; set; }
    }
}
