//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTIBD
    {
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string DOS { get; set; }
        public string RECDATE { get; set; }
        public string DOCTYPE { get; set; }
        public string WHO { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string DOCNO { get; set; }
        public string STATUS { get; set; }
        public string REASON { get; set; }
        public string IFN { get; set; }
        public string STARTSTEP { get; set; }
        public string DATATYPE { get; set; }
        public string CODETYPE { get; set; }
        public Nullable<long> COURIER_INST_ID { get; set; }
        public long PLX_COURIER_ID { get; set; }
        public string ACCTNUM { get; set; }
        public Nullable<int> NUMOFCHARTS { get; set; }
        public string RTIACCTNUM { get; set; }
        public string ACT_NAME { get; set; }
        public string MAP_NAME { get; set; }
        public Nullable<long> NODE_ID { get; set; }
        public Nullable<long> MAP_INST_ID { get; set; }
        public string EMTRAC { get; set; }
        public string SPARE1 { get; set; }
        public string USERNAME { get; set; }
        public string FINANCIAL_CLASS { get; set; }
        public string ESCALATION_REASON { get; set; }
        public string CORRECTION_FOLDER { get; set; }
    }
}
