//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTICLIENT
    {
        public string EMPRAC { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string CODETYPE { get; set; }
        public string RLOGGRP { get; set; }
        public string CODEGRP { get; set; }
        public string VERIFYGRP { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<System.DateTime> EFFDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> POST_EFFDATE { get; set; }
        public Nullable<System.DateTime> POST_ENDDATE { get; set; }
        public string HOSPITALIST { get; set; }
        public string CONTRACT_TYPE { get; set; }
        public string SERVER_NAME { get; set; }
        public string SERVER_NAME2 { get; set; }
        public Nullable<decimal> SERVER_PORT { get; set; }
        public string REX_DBNAME { get; set; }
        public string LOGICAL_DBNAME { get; set; }
        public string IQSERVER_NAME { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string STATUS { get; set; }
        public string REGION_ABBR { get; set; }
        public Nullable<decimal> CLIENT_LAG_DAYS { get; set; }
        public string PRACTICE_NAME { get; set; }
        public Nullable<decimal> DEFICIENCY_THRESHOLD { get; set; }
        public Nullable<decimal> DAILY_VOLUME { get; set; }
        public Nullable<decimal> DELINQUENT_CLASS { get; set; }
        public Nullable<decimal> OVERDUE_CLASS { get; set; }
        public string FACILITY_NAME { get; set; }
        public string AR_REGION { get; set; }
        public decimal RTICLIENT_ID { get; set; }
    }
}
