//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTIHIST
    {
        public string DOCNO { get; set; }
        public string STATUS { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string ACTIVITY { get; set; }
        public string CRE_DT_TM { get; set; }
        public string ENT_DT_TM { get; set; }
        public string USERID { get; set; }
        public string SPARE1 { get; set; }
        public Nullable<System.DateTime> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
    }
}
