//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCAN_LOG
    {
        public string BILL_AREA { get; set; }
        public string BATCH_ID { get; set; }
        public string MISSING_LOG { get; set; }
        public System.DateTime ADMIT_DATE { get; set; }
        public decimal PAT_LOG { get; set; }
        public Nullable<decimal> MISSINGS { get; set; }
        public Nullable<decimal> TOTAL_DOS { get; set; }
        public Nullable<decimal> TOTAL_CHARTS { get; set; }
        public Nullable<decimal> BACK_DATE { get; set; }
        public Nullable<decimal> SUSP_CHARTS { get; set; }
        public Nullable<decimal> NON_BILL { get; set; }
        public decimal ADD_ON { get; set; }
        public Nullable<decimal> TOTAL_PROCESS { get; set; }
        public Nullable<decimal> DICTATIONS { get; set; }
        public Nullable<decimal> O_HOSTNO { get; set; }
        public Nullable<decimal> O_PROCNO { get; set; }
        public Nullable<decimal> O_INSTNO { get; set; }
        public Nullable<decimal> O_HOSTID { get; set; }
        public string O_TYPEID { get; set; }
        public Nullable<decimal> O_OBJID { get; set; }
        public Nullable<decimal> O_REVID { get; set; }
    }
}
