//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIAL_IDS
    {
        public decimal SERIAL_ID { get; set; }
        public Nullable<decimal> CURRENT_ID { get; set; }
        public Nullable<decimal> CACHING_FACTOR { get; set; }
        public Nullable<decimal> TRANSACTION_NO { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> RESERVED1 { get; set; }
        public Nullable<decimal> RESERVED2 { get; set; }
    }
}
