//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLN_PROF_ANB
    {
        public decimal RUNID { get; set; }
        public decimal UNIT_NUMBER { get; set; }
        public decimal LINE_ { get; set; }
        public string TEXT { get; set; }
    }
}
