//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLN_PROF_SESS
    {
        public decimal RUNID { get; set; }
        public decimal STAT_ID { get; set; }
        public Nullable<decimal> VALUE { get; set; }
    
        public virtual PLSQL_PROFILER_RUNS PLSQL_PROFILER_RUNS { get; set; }
    }
}
