//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLN_PROF_PROFILES
    {
        public decimal PROJ_ID { get; set; }
        public string PROJ_NAME { get; set; }
        public string PROJ_COMMENT { get; set; }
    }
}
