//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STARTRULE_LOOKUP
    {
        public decimal STARTRULE_LOOKUP_ID { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCDET { get; set; }
        public string REASON { get; set; }
        public string SECURITY_GROUP { get; set; }
        public Nullable<decimal> SOURCETYPE_LOOKUP_ID { get; set; }
        public Nullable<decimal> POSTDETAIL_STATUS_LOOKUP_ID { get; set; }
    }
}
