//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_CONFIG
    {
        public long SERV_ID { get; set; }
        public long MAX_MAP_STAT_CNT { get; set; }
        public long MAX_MACT_STAT_CNT { get; set; }
        public long MAX_SACT_STAT_CNT { get; set; }
        public long MAX_USER_STAT_CNT { get; set; }
        public long STAT_ON { get; set; }
        public long STAT_MEM_KEY { get; set; }
        public long STAT_MEM_ID { get; set; }
        public long STAT_QKEY { get; set; }
        public long STAT_QID { get; set; }
        public long CRITICAL { get; set; }
        public string FLUSH_FILE { get; set; }
        public string STAT_DBNAME { get; set; }
        public string STAT_NAME { get; set; }
        public long DEF_PORT_NUM { get; set; }
    }
}
