//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STGACC
    {
        public decimal STGACC_ID { get; set; }
        public decimal STGPID_ID { get; set; }
        public Nullable<System.DateTime> ACTIVITYTIME { get; set; }
        public string CODE { get; set; }
        public string LOCATION { get; set; }
        public string ACCIDENTSTATE { get; set; }
        public string JOBRELATED { get; set; }
        public string MODELDEADLY { get; set; }
        public string MODELENTEREDBY { get; set; }
        public string ACCCOUNTRY { get; set; }
    }
}
