//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STGEVN
    {
        public decimal STGEVN_ID { get; set; }
        public decimal STGPID_ID { get; set; }
        public string EVENTTYPECODE { get; set; }
        public Nullable<System.DateTime> EVENTDATETIME { get; set; }
        public string OPERATORID { get; set; }
    }
}
