//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STGMSH
    {
        public decimal STGMSH_ID { get; set; }
        public string FIELDSEPARATOR { get; set; }
        public string ENCODINGCHARACTERS { get; set; }
        public string SENDINGAPPLICATION { get; set; }
        public string SENDINGFACILITY { get; set; }
        public string RECEIVINGAPPLICATION { get; set; }
        public string RECEIVINGFACILITY { get; set; }
        public Nullable<System.DateTime> MESSAGEDATETIME { get; set; }
        public string MESSAGETYPE { get; set; }
        public string MESSAGECONTROLID { get; set; }
        public string PROCESSINGID { get; set; }
        public string VERSIONID { get; set; }
        public string EVENTTYPECODE { get; set; }
        public Nullable<System.DateTime> EVENTRECORDEDDATETIME { get; set; }
        public Nullable<System.DateTime> CREATETIMESTAMP { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public Nullable<decimal> STAGE { get; set; }
    }
}
