//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STGNK1
    {
        public decimal STGNK1_ID { get; set; }
        public decimal STGPID_ID { get; set; }
        public Nullable<decimal> SETID { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string RELATIONSHIP { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
        public string BUSINESSPHONE { get; set; }
        public string MARITALSTATUSCODE { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public string KINCOUNTRY { get; set; }
        public string CONTACTROLE { get; set; }
    }
}
