//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STGPID
    {
        public decimal STGPID_ID { get; set; }
        public decimal STGMSH_ID { get; set; }
        public Nullable<decimal> SETID { get; set; }
        public string EXTERNALID_MRN { get; set; }
        public string INTERNALID { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public string SEX { get; set; }
        public string RACE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string HOMEPHONE { get; set; }
        public string BUSINESSPHONE { get; set; }
        public string MARITALSTATUSCODE { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string SSN { get; set; }
        public string PCPINFORMATION { get; set; }
        public Nullable<short> STUDENTINDICATOR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CHECKDIGIT { get; set; }
        public string COUNTRY { get; set; }
    }
}
