//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORRGRIDS_TBL
    {
        public string G { get; set; }
        public string G2 { get; set; }
        public string PBSBASE { get; set; }
        public string AD_ZONE { get; set; }
        public string AD_AREA { get; set; }
        public string VENAREA { get; set; }
        public Nullable<decimal> VENCRITERIA { get; set; }
        public string DHS_SUB { get; set; }
        public string JURIS { get; set; }
        public short HELLS_GATE { get; set; }
        public string MARKER { get; set; }
        public Nullable<decimal> PAGE { get; set; }
        public string GRID { get; set; }
        public string TBMKEY { get; set; }
        public string DEG_LAT { get; set; }
        public string DEG_LON { get; set; }
        public Nullable<decimal> DEC_LAT { get; set; }
        public Nullable<decimal> DEC_LON { get; set; }
        public string CENSUS { get; set; }
        public string CITY { get; set; }
        public string JURIS_2 { get; set; }
        public string GCAT { get; set; }
        public string GCODE { get; set; }
        public string GEONAME { get; set; }
        public string LAW_ENF { get; set; }
        public string FIRE_DEST { get; set; }
        public string CITY_DESC { get; set; }
        public Nullable<decimal> SUP_DIST { get; set; }
        public Nullable<decimal> CRITICAL_REGION { get; set; }
        public string SELECTED { get; set; }
        public Nullable<decimal> XCOORD { get; set; }
        public Nullable<decimal> YCOORD { get; set; }
        public string REGION { get; set; }
        public string OLDPAGE { get; set; }
        public string AZONE { get; set; }
        public string DISTRICT { get; set; }
        public string DISTRICT_1 { get; set; }
        public string AMBAREA { get; set; }
        public string NEWAREA { get; set; }
        public string R_GRIDS_VEN_CITY { get; set; }
        public string VENCO { get; set; }
        public Nullable<decimal> CRTIME { get; set; }
        public Nullable<decimal> DHS { get; set; }
        public string TDHS { get; set; }
        public string GEONAME_2 { get; set; }
        public string CAUTION { get; set; }
        public string PURGE { get; set; }
        public string ZIP { get; set; }
        public short CHANGE { get; set; }
    }
}
