//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOWERIMPORTCLIENT
    {
        public decimal TOWERIMPORTCLIENT_ID { get; set; }
        public decimal CLIENTID { get; set; }
        public string CLIENTNAME { get; set; }
        public string PRACTICE { get; set; }
        public string PRACTYPE { get; set; }
        public string CLIENTLOCATION { get; set; }
        public string REMOTELOCATION { get; set; }
        public string PRINTCHARTS { get; set; }
        public string PRINTCOVER { get; set; }
        public string COPYCHARTS { get; set; }
        public string BATCHFORMAT { get; set; }
        public string USEANNOTATIONS { get; set; }
        public string ANNXCOOR { get; set; }
        public string ANNYCOOR { get; set; }
        public string DELETEFIRSTPAGE { get; set; }
        public string APPENDTIF { get; set; }
        public decimal APPENDLOCATION { get; set; }
        public string APPENDTIFFILE { get; set; }
        public string MOVECHARTS { get; set; }
        public string MOVETOLOCATION { get; set; }
        public string PRINTERNAME { get; set; }
        public string FORMATTYPE { get; set; }
        public Nullable<decimal> LASTMODDT { get; set; }
        public string SELECTED { get; set; }
        public decimal LAGDAYS { get; set; }
        public string EREGIPATH { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string HOST_NAME { get; set; }
        public decimal BATCH_PRIORITY { get; set; }
        public Nullable<decimal> HASEREGI { get; set; }
        public Nullable<decimal> HASIBX { get; set; }
        public Nullable<decimal> HASEDLOG { get; set; }
        public Nullable<decimal> DEFAULT_SCENARIO { get; set; }
        public string HL7FILECLIENTCODE { get; set; }
        public decimal PAGELIMIT { get; set; }
        public decimal BATCHCUTOFF { get; set; }
        public string FTPSOURCE { get; set; }
        public string AUTO_BDBATCH { get; set; }
    }
}
