//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TowerModelContainer : DbContext
    {
        public TowerModelContainer()
            : base("name=TowerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AMRBILLEXT> AMRBILLEXTs { get; set; }
        public DbSet<AMRPOSTEXT> AMRPOSTEXTs { get; set; }
        public DbSet<AR_REGION> AR_REGION { get; set; }
        public DbSet<BILLDOCEXT> BILLDOCEXTs { get; set; }
        public DbSet<IMAGEINFO_USERS> IMAGEINFO_USERS { get; set; }
        public DbSet<PATIENT_VOLUME> PATIENT_VOLUME { get; set; }
        public DbSet<POSTDOCEXT> POSTDOCEXTs { get; set; }
        public DbSet<WF_INVENTORY> WF_INVENTORY { get; set; }
        public DbSet<WF_PRODUCTIVITY> WF_PRODUCTIVITY { get; set; }
        public DbSet<AMRBILL> AMRBILLs { get; set; }
        public DbSet<AMRBILL_HISTORY> AMRBILL_HISTORY { get; set; }
        public DbSet<AMRDISCOVERY> AMRDISCOVERies { get; set; }
        public DbSet<AMRDISCOVERY_VIEW1> AMRDISCOVERY_VIEW1 { get; set; }
        public DbSet<AMRDISCOVERY_VIEW3> AMRDISCOVERY_VIEW3 { get; set; }
        public DbSet<AMRDISCOVERY_VIEW4> AMRDISCOVERY_VIEW4 { get; set; }
        public DbSet<AMRPOST> AMRPOSTs { get; set; }
        public DbSet<AMRPOST_HISTORY> AMRPOST_HISTORY { get; set; }
        public DbSet<AMRPOSTDETAIL> AMRPOSTDETAILs { get; set; }
        public DbSet<AMRPOSTWAKE> AMRPOSTWAKEs { get; set; }
        public DbSet<AMRPOSTWAKE_DEL> AMRPOSTWAKE_DEL { get; set; }
        public DbSet<AMRWFWAKE> AMRWFWAKEs { get; set; }
        public DbSet<AMRWFWAKE_DEL> AMRWFWAKE_DEL { get; set; }
        public DbSet<ANNOTTBL> ANNOTTBLs { get; set; }
        public DbSet<B_LIST> B_LIST { get; set; }
        public DbSet<B_MAP> B_MAP { get; set; }
        public DbSet<B2D> B2D { get; set; }
        public DbSet<B3D> B3D { get; set; }
        public DbSet<B4D> B4D { get; set; }
        public DbSet<BAMRBILL> BAMRBILLs { get; set; }
        public DbSet<BAMRPOST> BAMRPOSTs { get; set; }
        public DbSet<BBILLDOC> BBILLDOCs { get; set; }
        public DbSet<BILLDOC> BILLDOCs { get; set; }
        public DbSet<BPOSTDOC> BPOSTDOCs { get; set; }
        public DbSet<COURIER_RELOCATE> COURIER_RELOCATE { get; set; }
        public DbSet<DEPOSITCLIENT> DEPOSITCLIENTs { get; set; }
        public DbSet<DOCDETAIL_LOOKUP> DOCDETAIL_LOOKUP { get; set; }
        public DbSet<DOCLIST> DOCLISTs { get; set; }
        public DbSet<DOCTYPE_LOOKUP> DOCTYPE_LOOKUP { get; set; }
        public DbSet<FLDINFO> FLDINFOes { get; set; }
        public DbSet<FTBL> FTBLs { get; set; }
        public DbSet<FULLBALANCE_REQUEST> FULLBALANCE_REQUEST { get; set; }
        public DbSet<POSTBD> POSTBDs { get; set; }
        public DbSet<POSTDETAIL> POSTDETAILs { get; set; }
        public DbSet<POSTDETAIL_STATUS_LOOKUP> POSTDETAIL_STATUS_LOOKUP { get; set; }
        public DbSet<POSTDOC> POSTDOCs { get; set; }
        public DbSet<POSTDOC_STATUS_LOOKUP> POSTDOC_STATUS_LOOKUP { get; set; }
        public DbSet<POSTWAKE> POSTWAKEs { get; set; }
        public DbSet<POSTWAKE_DEL> POSTWAKE_DEL { get; set; }
        public DbSet<REASON_LOOKUP> REASON_LOOKUP { get; set; }
        public DbSet<RTIBD> RTIBDs { get; set; }
        public DbSet<RTIHIST> RTIHISTs { get; set; }
        public DbSet<RTIWAKE> RTIWAKEs { get; set; }
        public DbSet<SCAN_LOG> SCAN_LOG { get; set; }
        public DbSet<SOURCETYPE_LOOKUP> SOURCETYPE_LOOKUP { get; set; }
        public DbSet<TABINFO> TABINFOes { get; set; }
        public DbSet<TTBL> TTBLs { get; set; }
        public DbSet<WFWAKE> WFWAKEs { get; set; }
        public DbSet<WFWAKE_DEL> WFWAKE_DEL { get; set; }
        public DbSet<GROUPATTRIBUTE> GROUPATTRIBUTES { get; set; }
        public DbSet<USERATTRIBUTE> USERATTRIBUTES { get; set; }
        public DbSet<STARTRULE_LOOKUP> STARTRULE_LOOKUP { get; set; }
        public DbSet<RTICLIENT> RTICLIENTs { get; set; }
        public DbSet<CRUDRULE> CRUDRULES { get; set; }
        public DbSet<BPRRULE> BPRRULES { get; set; }
    }
}
