//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOWERIMPORT
    {
        public decimal TOWERIMPORT_ID { get; set; }
        public decimal EMSCANIMAGEKEY { get; set; }
        public decimal CADKEY { get; set; }
        public decimal CLIENTKEY { get; set; }
        public System.DateTime DOS { get; set; }
        public string FILENAME { get; set; }
        public string ISNEW { get; set; }
        public System.DateTime ENTRYDATE { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public Nullable<System.DateTime> LASTMODDATE { get; set; }
        public string ENCTRNO { get; set; }
        public string ISMATCHED { get; set; }
        public string FILEEND { get; set; }
        public decimal RECTYPE { get; set; }
        public Nullable<decimal> PURGEDATE { get; set; }
        public Nullable<decimal> EXCEPTIONKEY { get; set; }
        public string FILESIZE { get; set; }
        public string CSTATUS { get; set; }
        public string LNAME { get; set; }
        public string FNAME { get; set; }
        public string DOCNO { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
        public decimal EMSCANBATCHKEY { get; set; }
        public decimal EMSCANDOCKEY { get; set; }
        public decimal FILETYPE { get; set; }
        public decimal DEFAULT_SCENARIO { get; set; }
        public decimal CURRENT_SCENARIO { get; set; }
        public string DISPOSITION { get; set; }
    }
}
