//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTBL
    {
        public string TNAME { get; set; }
        public string ANAME { get; set; }
        public Nullable<decimal> THEIGHT { get; set; }
        public Nullable<decimal> TWIDTH { get; set; }
        public Nullable<decimal> NINPFLDS { get; set; }
        public Nullable<decimal> NOUTFLDS { get; set; }
        public string SCRIPTFL { get; set; }
        public decimal TOWID { get; set; }
    }
}
