//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public long USER_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public long MAP_NAME_ID { get; set; }
        public long ACT_NAME_ID { get; set; }
        public long LOGIN_LIMIT { get; set; }
        public long LOGIN_COUNT { get; set; }
        public long DELETE_FLAG { get; set; }
        public long ACCESS_LEVEL { get; set; }
        public long MAP_PRIVILEGE { get; set; }
        public long USER_STATUS { get; set; }
        public long LOCK_FLAG { get; set; }
        public string MAIL_ADDRESS { get; set; }
    }
}
