//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GROUPS
    {
        public long USERGRP_ID { get; set; }
        public long USERGRP_MBR_TYPE { get; set; }
        public long USERGRP_MBR_ID { get; set; }
    }
}
