//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERATTRIBUTE
    {
        public string USERNAME { get; set; }
        public string USERATTRIBUTEKEY { get; set; }
        public string USERATTRIBUTEVALUE { get; set; }
        public Nullable<System.DateTime> CREATEDTIMESTAMP { get; set; }
        public Nullable<System.DateTime> MODIFIEDTIMESTAMP { get; set; }
    }
}
