//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TEST1
    {
        public decimal POSTDETAIL_ID { get; set; }
        public Nullable<decimal> POSTDETAIL_TOWER_ID { get; set; }
        public decimal POSTDOC_TOWER_ID { get; set; }
        public string DOCNUM { get; set; }
        public string PARENT_DOCNUM { get; set; }
        public string ORIG_DOCNUM { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
    }
}
