//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARIABLE
    {
        public long VARIABLE_NAME_ID { get; set; }
        public string VARIABLE_NAME { get; set; }
        public long SCOPE { get; set; }
        public long DATATYPE { get; set; }
        public long ACCESS_LEVEL { get; set; }
        public string DESCRIPTION { get; set; }
        public long LOCK_FLAG { get; set; }
        public long VALUE_LOCK_FLAG { get; set; }
        public string BUS_TABLE_NAME { get; set; }
        public string BUS_COLUMN_NAME { get; set; }
        public Nullable<long> LENGTH { get; set; }
    }
}
