//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_CURRENCY
    {
        public long VARIABLE_NAME_ID { get; set; }
        public long COURIER_ID { get; set; }
        public decimal VARIABLE_VALUE { get; set; }
    }
}
