//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FINANCIAL_CLASSES
    {
        public string FINANCIAL_CLASS_CODE { get; set; }
        public string FINANCIAL_CLASS_DESC { get; set; }
        public string STATUS { get; set; }
    }
}
