//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_INVENTORY
    {
        public Nullable<long> WF_INVENTORY_ID { get; set; }
        public System.DateTime WF_DATE { get; set; }
        public string MAP_NAME { get; set; }
        public string ACTIVITY_NAME { get; set; }
        public string PRACTICE { get; set; }
        public string DIVISION { get; set; }
        public string CODE_TYPE { get; set; }
        public string FINANCIAL_CLASS { get; set; }
        public Nullable<long> ITEM_COUNT { get; set; }
        public string DOCTYPE { get; set; }
    }
}
