//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOOD
    {
        public string OWNER { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLESPACE_NAME { get; set; }
        public string CLUSTER_NAME { get; set; }
        public string IOT_NAME { get; set; }
        public Nullable<decimal> PCT_FREE { get; set; }
        public Nullable<decimal> PCT_USED { get; set; }
        public Nullable<decimal> INI_TRANS { get; set; }
        public Nullable<decimal> MAX_TRANS { get; set; }
        public Nullable<decimal> INITIAL_EXTENT { get; set; }
        public Nullable<decimal> NEXT_EXTENT { get; set; }
        public Nullable<decimal> MIN_EXTENTS { get; set; }
        public Nullable<decimal> MAX_EXTENTS { get; set; }
        public Nullable<decimal> PCT_INCREASE { get; set; }
        public Nullable<decimal> FREELISTS { get; set; }
        public Nullable<decimal> FREELIST_GROUPS { get; set; }
        public string LOGGING { get; set; }
        public string BACKED_UP { get; set; }
        public Nullable<decimal> NUM_ROWS { get; set; }
        public Nullable<decimal> BLOCKS { get; set; }
        public Nullable<decimal> EMPTY_BLOCKS { get; set; }
        public Nullable<decimal> AVG_SPACE { get; set; }
        public Nullable<decimal> CHAIN_CNT { get; set; }
        public Nullable<decimal> AVG_ROW_LEN { get; set; }
        public Nullable<decimal> AVG_SPACE_FREELIST_BLOCKS { get; set; }
        public Nullable<decimal> NUM_FREELIST_BLOCKS { get; set; }
        public string DEGREE { get; set; }
        public string INSTANCES { get; set; }
        public string CACHE { get; set; }
        public string TABLE_LOCK { get; set; }
        public Nullable<decimal> SAMPLE_SIZE { get; set; }
        public Nullable<System.DateTime> LAST_ANALYZED { get; set; }
        public string PARTITIONED { get; set; }
        public string IOT_TYPE { get; set; }
        public string TEMPORARY { get; set; }
        public string SECONDARY { get; set; }
        public string NESTED { get; set; }
        public string BUFFER_POOL { get; set; }
        public string ROW_MOVEMENT { get; set; }
        public string GLOBAL_STATS { get; set; }
        public string USER_STATS { get; set; }
        public string DURATION { get; set; }
        public string SKIP_CORRUPT { get; set; }
        public string MONITORING { get; set; }
        public string CLUSTER_OWNER { get; set; }
        public string DEPENDENCIES { get; set; }
        public string COMPRESSION { get; set; }
    }
}
