//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rti.InternalInterfaces.DataContracts
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Login.UserCredentials", Namespace = "http://schemas.datacontract.org/2004/07/Rti.InternalInterfaces.DataContracts")]
    public partial class LoginUserCredentials : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        public void UserCredentials(string unixUserName, string unixPassword, string windowsDomain)
        {
            UnixUserName = unixUserName;
            UnixPassword = unixPassword;
            WindowsDomain = windowsDomain;
        }

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string FetchOptionsField;

        private bool SetContextField;

        private string UnixPasswordField;

        private string UnixUserNameField;

        private string WindowsDomainField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FetchOptions
        {
            get
            {
                return this.FetchOptionsField;
            }
            set
            {
                this.FetchOptionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SetContext
        {
            get
            {
                return this.SetContextField;
            }
            set
            {
                this.SetContextField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnixPassword
        {
            get
            {
                return this.UnixPasswordField;
            }
            set
            {
                this.UnixPasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnixUserName
        {
            get
            {
                return this.UnixUserNameField;
            }
            set
            {
                this.UnixUserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsDomain
        {
            get
            {
                return this.WindowsDomainField;
            }
            set
            {
                this.WindowsDomainField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Login.Permissions", Namespace = "http://schemas.datacontract.org/2004/07/Rti.InternalInterfaces.DataContracts")]
    public partial class LoginPermissions : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Rti.InternalInterfaces.DataContracts.LoginPermissions.AssemblyPermissions AssemblyField;

        private string EmBillzUsernameField;

        private Rti.InternalInterfaces.DataContracts.LoginPermissions.IDMPermissions IDMField;

        private string LoginMessageField;

        private bool LoginSuccessfulField;

        private string UnixUsernameField;

        private string UserGroupField;

        private string WindowsUsernameField;

        private Rti.InternalInterfaces.DataContracts.LoginPermissions.WorkFlowPermissions WorkFlowField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rti.InternalInterfaces.DataContracts.LoginPermissions.AssemblyPermissions Assembly
        {
            get
            {
                return this.AssemblyField;
            }
            set
            {
                this.AssemblyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmBillzUsername
        {
            get
            {
                return this.EmBillzUsernameField;
            }
            set
            {
                this.EmBillzUsernameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rti.InternalInterfaces.DataContracts.LoginPermissions.IDMPermissions IDM
        {
            get
            {
                return this.IDMField;
            }
            set
            {
                this.IDMField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginMessage
        {
            get
            {
                return this.LoginMessageField;
            }
            set
            {
                this.LoginMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LoginSuccessful
        {
            get
            {
                return this.LoginSuccessfulField;
            }
            set
            {
                this.LoginSuccessfulField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnixUsername
        {
            get
            {
                return this.UnixUsernameField;
            }
            set
            {
                this.UnixUsernameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGroup
        {
            get
            {
                return this.UserGroupField;
            }
            set
            {
                this.UserGroupField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsUsername
        {
            get
            {
                return this.WindowsUsernameField;
            }
            set
            {
                this.WindowsUsernameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rti.InternalInterfaces.DataContracts.LoginPermissions.WorkFlowPermissions WorkFlow
        {
            get
            {
                return this.WorkFlowField;
            }
            set
            {
                this.WorkFlowField = value;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "Login.Permissions.AssemblyPermissions", Namespace = "http://schemas.datacontract.org/2004/07/Rti.InternalInterfaces.DataContracts")]
        public partial class AssemblyPermissions : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private bool CanApproveMatchField;

            private bool CanAssembleAllField;

            private bool CanDeleteField;

            private bool CanPendMatchField;

            private bool CanUpdateField;

            private bool CanViewField;

            private string ExperienceField;

            private bool IsAutoViewField;

            private bool IsSupervisorField;

            private string SupervisorIdField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanApproveMatch
            {
                get
                {
                    return this.CanApproveMatchField;
                }
                set
                {
                    this.CanApproveMatchField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanAssembleAll
            {
                get
                {
                    return this.CanAssembleAllField;
                }
                set
                {
                    this.CanAssembleAllField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanDelete
            {
                get
                {
                    return this.CanDeleteField;
                }
                set
                {
                    this.CanDeleteField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanPendMatch
            {
                get
                {
                    return this.CanPendMatchField;
                }
                set
                {
                    this.CanPendMatchField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanUpdate
            {
                get
                {
                    return this.CanUpdateField;
                }
                set
                {
                    this.CanUpdateField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanView
            {
                get
                {
                    return this.CanViewField;
                }
                set
                {
                    this.CanViewField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Experience
            {
                get
                {
                    return this.ExperienceField;
                }
                set
                {
                    this.ExperienceField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsAutoView
            {
                get
                {
                    return this.IsAutoViewField;
                }
                set
                {
                    this.IsAutoViewField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsSupervisor
            {
                get
                {
                    return this.IsSupervisorField;
                }
                set
                {
                    this.IsSupervisorField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string SupervisorId
            {
                get
                {
                    return this.SupervisorIdField;
                }
                set
                {
                    this.SupervisorIdField = value;
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "Login.Permissions.IDMPermissions", Namespace = "http://schemas.datacontract.org/2004/07/Rti.InternalInterfaces.DataContracts")]
        public partial class IDMPermissions : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private string AnnotateAllField;

            private string AnnotateGroupField;

            private bool CanAdminAnnotationsField;

            private bool CanAnnotateField;

            private bool CanAppendField;

            private bool CanExportField;

            private bool CanImportField;

            private bool CanModifyField;

            private bool CanModifyAnnotationsField;

            private bool CanModifyTitleField;

            private bool CanPrintField;

            private bool CanViewAnnotationsField;

            private string DefaultApplicationField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AnnotateAll
            {
                get
                {
                    return this.AnnotateAllField;
                }
                set
                {
                    this.AnnotateAllField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AnnotateGroup
            {
                get
                {
                    return this.AnnotateGroupField;
                }
                set
                {
                    this.AnnotateGroupField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanAdminAnnotations
            {
                get
                {
                    return this.CanAdminAnnotationsField;
                }
                set
                {
                    this.CanAdminAnnotationsField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanAnnotate
            {
                get
                {
                    return this.CanAnnotateField;
                }
                set
                {
                    this.CanAnnotateField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanAppend
            {
                get
                {
                    return this.CanAppendField;
                }
                set
                {
                    this.CanAppendField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanExport
            {
                get
                {
                    return this.CanExportField;
                }
                set
                {
                    this.CanExportField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanImport
            {
                get
                {
                    return this.CanImportField;
                }
                set
                {
                    this.CanImportField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanModify
            {
                get
                {
                    return this.CanModifyField;
                }
                set
                {
                    this.CanModifyField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanModifyAnnotations
            {
                get
                {
                    return this.CanModifyAnnotationsField;
                }
                set
                {
                    this.CanModifyAnnotationsField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanModifyTitle
            {
                get
                {
                    return this.CanModifyTitleField;
                }
                set
                {
                    this.CanModifyTitleField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanPrint
            {
                get
                {
                    return this.CanPrintField;
                }
                set
                {
                    this.CanPrintField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanViewAnnotations
            {
                get
                {
                    return this.CanViewAnnotationsField;
                }
                set
                {
                    this.CanViewAnnotationsField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string DefaultApplication
            {
                get
                {
                    return this.DefaultApplicationField;
                }
                set
                {
                    this.DefaultApplicationField = value;
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "Login.Permissions.WorkFlowPermissions", Namespace = "http://schemas.datacontract.org/2004/07/Rti.InternalInterfaces.DataContracts")]
        public partial class WorkFlowPermissions : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private bool CanAutoViewField;

            private bool IsSupervisorField;

            private string SupervisorField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool CanAutoView
            {
                get
                {
                    return this.CanAutoViewField;
                }
                set
                {
                    this.CanAutoViewField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsSupervisor
            {
                get
                {
                    return this.IsSupervisorField;
                }
                set
                {
                    this.IsSupervisorField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Supervisor
            {
                get
                {
                    return this.SupervisorField;
                }
                set
                {
                    this.SupervisorField = value;
                }
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IAdministrationService")]
public interface IAdministrationService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAdministrationService/IsAlive", ReplyAction = "http://tempuri.org/IAdministrationService/IsAliveResponse")]
    bool IsAlive();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAdministrationService/EmWareCollectionLogin", ReplyAction = "http://tempuri.org/IAdministrationService/EmWareCollectionLoginResponse")]
    Rti.InternalInterfaces.DataContracts.LoginPermissions EmWareCollectionLogin(string workstation, string username, Rti.InternalInterfaces.DataContracts.Login.UserCredentials loginCredentials);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAdministrationServiceChannel : IAdministrationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AdministrationServiceClient : System.ServiceModel.ClientBase<IAdministrationService>, IAdministrationService
{

    public AdministrationServiceClient()
    {
    }

    public AdministrationServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public AdministrationServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public AdministrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public AdministrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public bool IsAlive()
    {
        return base.Channel.IsAlive();
    }

    public Rti.InternalInterfaces.DataContracts.LoginPermissions EmWareCollectionLogin(string workstation, string username, Rti.InternalInterfaces.DataContracts.Login.UserCredentials loginCredentials)
    {
        return base.Channel.EmWareCollectionLogin(workstation, username, loginCredentials);
    }
}
