using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace WpfDocViewer.Model
{
    public class ImportDataModel
    {

        //Index Details  
        public string DocumentNumber { get; set; }
        public string ParentDocumentNumber { get; set; }
        public string OriginalDocumentNumber { get; set; }
        public bool ManuallyEnter { get; set; }

        //Needs Prepping
        public Boolean NeedsPrepping { get; set; }
        public Boolean RemitOnly { get; set; }
        public string CheckNumber { get; set; }
        public double CheckAmount { get; set; }
        public string DepositDate { get; set; }
        public bool AutogenerateDSeq { get; set; }
        public int SequenceNumber { get; set; }

        
        public bool OverWriteDRoutingInfo { get; set; }

        //Account Details
        public string AccountNumber { get; set; }
        public string DepartmentCode { get; set; }
        public string ExtPayor { get; set; }
        public List<string> Practice { get; set; }
        public List<string> Divisions { get; set; }
        public List<string> ServiceIds { get; set; }
        public class DocumentType
        {
            public string key { get; set; }
            public string description { get; set; }
            public string fullDocTypeDescription { get; set; }
        }
        public class DocumentDetail
        {
            public string detailkey { get; set; }
            public string detaildescription { get; set; }
            public string fullDetailDescription { get; set; }
        }
        public class StartActivity
        {
            public string typecode { get; set; }
            public string startdescription { get; set; }
            public string fullstartActivityDesc { get; set; }
            public string mapName { get; set; }
            public string activityName { get; set; }
        }
        public class DocumentSource
        {
            public string sourceTypecode { get; set; }
            public string sourceDescription { get; set; }
            public string fullsourceDescription { get; set; }
        }



    }

}
