//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IReportingService")]
public interface IReportingService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportingService/IsAlive", ReplyAction = "http://tempuri.org/IReportingService/IsAliveResponse")]
    bool IsAlive();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IReportingServiceChannel : IReportingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ReportingServiceClient : System.ServiceModel.ClientBase<IReportingService>, IReportingService
{

    public ReportingServiceClient()
    {
    }

    public ReportingServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public ReportingServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ReportingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ReportingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public bool IsAlive()
    {
        return base.Channel.IsAlive();
    }
}
